# scripts/build_full_expansion.py
# High quality authentic C2 expansion items to exceed 1,000 total questions

ADDITIONAL_CLOZE = [
    # Key Word Transformations
    ("transformation", "KWT: Idioms with 'Tether'", 4,
     "She was completely exhausted and at the limit of her patience.", "TETHER",
     "She was at the very ", " her patience.",
     ["end of her tether with", "end of her tether and"],
     "Use 'at the end of one's tether'.",
     "'At the end of one's tether' means having exhausted endurance or patience.",
     "Exhausted by constant delays, the travelers were at the end of their tether."),

    ("transformation", "KWT: Mixed Conditionals", 5,
     "If he hadn't broken his collarbone, he would be playing in the final today.", "FOR",
     "Had ", " broken collarbone, he would be playing in the final today.",
     ["it not been for his", "it not been for that"],
     "Use inverted conditional 'Had it not been for...'.",
     "'Had it not been for + noun' expresses counterfactual condition.",
     "Had it not been for his prompt rescue, the sailors would have perished."),

    ("transformation", "KWT: Concessive 'Much as'", 4,
     "Although I admire her dedication, I cannot endorse her aggressive tactics.", "MUCH",
     "Much ", " her dedication, I cannot endorse her aggressive tactics.",
     ["as I admire", "though I admire"],
     "Use 'Much as + subject + verb' for strong concession.",
     "'Much as' is a formal concessive connective meaning 'although very much'.",
     "Much as I respect your opinion, I must follow regulatory protocol."),

    ("transformation", "KWT: Passive with 'Thought'", 4,
     "Historians believe that the fortress was built during the reign of Justinian.", "THOUGHT",
     "The fortress is ", " during the reign of Justinian.",
     ["thought to have been built", "thought to be built"],
     "Use personal passive: 'is thought to have been built'.",
     "Personal passive with perfect infinitive reflects past belief.",
     "The castle is thought to have been erected around 1250."),

    ("transformation", "KWT: Result with 'Such'", 5,
     "The fog was so dense that all inbound international flights were diverted.", "SUCH",
     "Such ", " that all inbound international flights were diverted.",
     ["was the density of the fog", "was the fog"],
     "Use inverted 'Such was the + noun + that...'.",
     "Emphatic inversion: 'Such was the violence of the storm that roofs were torn off.'",
     "Such was the intensity of the heat that the tarmac melted."),

    ("transformation", "KWT: Nominalization with 'Sight'", 4,
     "As soon as the sailors saw the lighthouse, they cheered with relief.", "SIGHT",
     "At ", " the lighthouse, the sailors cheered with relief.",
     ["the sight of", "first sight of"],
     "Use 'At the sight of + noun'.",
     "Nominalization transforms 'as soon as they saw' into 'At the sight of'.",
     "At the sight of the cavalry, the opposing forces retreated."),

    ("transformation", "KWT: Idioms with 'Grip'", 4,
     "He finally managed to control his mounting panic and think rationally.", "GRIPS",
     "He finally managed to ", " his mounting panic and think rationally.",
     ["come to grips with", "get to grips with"],
     "Use 'come to grips with' or 'get to grips with'.",
     "'To get to grips with' means to begin to understand or successfully deal with a challenging problem.",
     "It took several months for the novice prime minister to get to grips with foreign policy."),

    ("transformation", "KWT: Prepositional Phrase 'Virtue'", 4,
     "She gained admission to the elite academy because of her exceptional piano talent.", "VIRTUE",
     "She gained admission to the elite academy by ", " her exceptional piano talent.",
     ["virtue of", "the virtue of"],
     "Use the prepositional phrase 'by virtue of'.",
     "'By virtue of' means because of or on account of.",
     "She succeeded by virtue of tenacity and unwavering discipline."),

    ("transformation", "KWT: Idiom 'Spur'", 4,
     "Without any prior planning, they booked a flight to Reykjavik.", "SPUR",
     "On the ", " they booked a flight to Reykjavik.",
     ["spur of the moment", "spur of that moment"],
     "Use the fixed idiom 'on the spur of the moment'.",
     "'On the spur of the moment' indicates acting impulsively without premeditation.",
     "We packed our backpacks on the spur of the moment and headed for the coast."),

    ("transformation", "KWT: Negative Inversion 'Account'", 5,
     "You must not disclose the confidential security protocols under any circumstances.", "ACCOUNT",
     "On ", " disclose the confidential security protocols.",
     ["no account should you", "no account must you"],
     "Use inverted 'On no account + modal + subject'.",
     "'On no account' triggers subject-auxiliary inversion.",
     "On no account should laboratory chemicals be discarded down the drain."),

    ("transformation", "KWT: Idiom 'Lurch'", 4,
     "His sudden resignation left his business partners in a very vulnerable position.", "LURCH",
     "His sudden resignation left his business partners in ", ".",
     ["the lurch", "a lurch"],
     "Use 'leave someone in the lurch'.",
     "'To leave someone in the lurch' means to abandon someone in a difficult situation.",
     "He walked out on the project, leaving his colleagues completely in the lurch."),

    ("transformation", "KWT: Phrasal 'Light'", 4,
     "Secret state documents revealed that corruption was widespread in the department.", "LIGHT",
     "Secret state documents brought ", " widespread corruption in the department.",
     ["to light the", "to light"],
     "Use 'bring to light'.",
     "'To bring something to light' means to disclose or make secret facts known.",
     "The investigation brought to light extensive financial irregularities."),

    ("transformation", "KWT: Idiom 'Bounds'", 4,
     "His enthusiastic curiosity had no limits whatsoever.", "BOUNDS",
     "His enthusiastic curiosity knew ", ".",
     ["no bounds", "no bound"],
     "Use 'know no bounds'.",
     "'To know no bounds' describes an emotion or quality that is boundless.",
     "Her generosity towards orphanages knew no bounds."),

    ("transformation", "KWT: Inversion 'Sooner'", 5,
     "Immediately after they signed the treaty, hostilities broke out again.", "SOONER",
     "No ", " the treaty than hostilities broke out again.",
     ["sooner had they signed", "sooner had the parties signed"],
     "Use correlative 'No sooner had + subject + past participle ... than'.",
     "'No sooner... than' requires past perfect inversion in the initial clause.",
     "No sooner had the curtain fallen than thunderous applause erupted."),

    ("transformation", "KWT: Idiom 'Stones'", 4,
     "The forensic team did everything possible to discover the truth.", "STONES",
     "The forensic team left no ", " discover the truth.",
     ["stone unturned in order to", "stones unturned to", "stone unturned to"],
     "Use 'leave no stone unturned'.",
     "'To leave no stone unturned' means to use every possible means to achieve an aim.",
     "Detectives left no stone unturned in their search for the missing heirloom."),

    ("transformation", "KWT: Verb 'Bear'", 4,
     "The detective was unable to prove that the suspect was connected to the theft.", "BEAR",
     "The detective could not bring any evidence to ", " the suspect's connection to the theft.",
     ["bear upon", "bear on"],
     "Use 'bring to bear upon/on'.",
     "'To bring to bear on' means to apply influence or pressure, or direct relevant evidence towards an issue.",
     "Significant diplomatic pressure was brought to bear on the rogue regime."),

    ("transformation", "KWT: Idiom 'Stretch'", 5,
     "The proposed budget cannot realistically be described as generous.", "STRETCH",
     "By no ", " described as generous.",
     ["stretch of the imagination can the budget be", "stretch of the imagination is the budget"],
     "Use 'by no stretch of the imagination'.",
     "'By no stretch of the imagination' emphasizes that something is utterly untrue or impossible.",
     "By no stretch of the imagination could the squalid motel be called luxury."),

    ("transformation", "KWT: Idiom 'Odds'", 4,
     "His eccentric behavior was entirely inconsistent with his dignified reputation.", "ODDS",
     "His eccentric behavior was completely at ", " his dignified reputation.",
     ["odds with", "odds alongside"],
     "Use 'at odds with'.",
     "'At odds with' means in conflict or at variance with something.",
     "His reckless remarks were completely at odds with official party policy."),

    ("transformation", "KWT: Idiom 'Wonders'", 3,
     "A brisk morning walk in the pine forest made her feel much more energetic.", "WONDERS",
     "A brisk morning walk in the pine forest did ", " her energy levels.",
     ["wonders for", "wonders to"],
     "Use 'do wonders for'.",
     "'To do wonders for' means to have a remarkably beneficial effect upon.",
     "A fortnight at the seaside did wonders for his recuperation."),

    ("transformation", "KWT: Phrasal 'Chalk'", 4,
     "The coach attributed the humiliating defeat to a lack of preparation.", "CHALKED",
     "The coach ", " a lack of preparation.",
     ["chalked the defeat up to", "chalked the humiliating defeat up to"],
     "Use 'chalk something up to'.",
     "'To chalk up to' means to ascribe an outcome or failure to a particular cause.",
     "We chalked our rookie blunders up to inexperience."),

    ("transformation", "KWT: Cleft 'What'", 4,
     "I only realized the gravity of the situation after reading the autopsy report.", "WHAT",
     "Only after reading the autopsy report ", " the gravity of the situation.",
     ["did I realize", "was it that I realized"],
     "Use inverted 'Only after... did I realize'.",
     "Fronted restrictive time adverbials require subject-auxiliary inversion.",
     "Only after consulting the archive did the historian uncover the forgery."),

    ("transformation", "KWT: Idiom 'Exception'", 4,
     "The ambassador strongly objected to the disparaging tone of the editorial.", "EXCEPTION",
     "The ambassador took ", " the disparaging tone of the editorial.",
     ["exception to", "great exception to"],
     "Use 'take exception to'.",
     "'To take exception to' means to object strongly to or be offended by something.",
     "I take great exception to the implication that our financial records were falsified."),

    ("transformation", "KWT: Nominalization 'Doubt'", 4,
     "There is no question that climate volatility has accelerated global desertification.", "CASTS",
     "Nobody ", " that climate volatility has accelerated global desertification.",
     ["casts any doubt on the fact", "casts doubt upon the fact"],
     "Use 'cast doubt on/upon'.",
     "'To cast doubt on' means to cause something to be questioned or considered uncertain.",
     "Recent satellite readings cast serious doubt on the initial meteorological forecast."),

    ("transformation", "KWT: Idiom 'Bay'", 4,
     "Antibiotic treatments successfully prevented the bacterial infection from spreading.", "BAY",
     "Antibiotic treatments kept the bacterial ", ".",
     ["infection at bay", "infection well at bay"],
     "Use 'keep at bay'.",
     "'To keep something at bay' means to hold back an adverse force or illness.",
     "The campfire kept nocturnal predators at bay throughout the night."),

    ("transformation", "KWT: Impersonal Passive 'Belief'", 4,
     "Contrary to what most laymen believe, venomous snakes rarely attack unprovoked.", "POPULAR",
     "Contrary to ", " venomous snakes rarely attack unprovoked.",
     ["popular belief", "popularly held belief"],
     "Use 'contrary to popular belief'.",
     "'Popular belief' is the standard C2 collocated phrase for widely held misconceptions.",
     "Contrary to popular belief, bats possess remarkably functional eyesight."),

    # Contextual Multiple Choice Cloze items (80 items)
    ("choice", "Cloze: Formal Nuance", 4,
     "The board commended the manager for her ________ handling of the delicate shareholder conflict.",
     ["adroit", "awkward", "ponderous", "clumsy"],
     "'Adroit' means clever or skillful in using the hands or mind, especially in diplomatic situations.",
     "Her adroit handling of the hostile takeover averted a boardroom revolt."),

    ("choice", "Cloze: Discourse Markers", 4,
     "The initial findings seemed promising; ________, subsequent clinical trials failed to replicate them.",
     ["nonetheless", "furthermore", "likewise", "moreover"],
     "'Nonetheless' acts as an adversative connective indicating contrast with the preceding statement.",
     "The company faced stiff head-winds; nonetheless, dividend payments remained steady."),

    ("choice", "Cloze: Precision Verbs", 4,
     "The prosecutor attempted to ________ inconsistencies in the alibi presented by the witness.",
     ["pinpoint", "flounder", "blunder", "skirt"],
     "'To pinpoint' means to find or locate with absolute precision.",
     "Satellite telemetry enabled engineers to pinpoint the structural failure on the hull."),

    ("choice", "Cloze: Evaluative Adjectives", 5,
     "His speech was replete with ________ flattery aimed solely at currying favor with the ministers.",
     ["fulsome", "curt", "laconic", "sparse"],
     "'Fulsome' in high register means excessively complimentary or lavish to an insincere degree.",
     "The courtiers plied the monarch with fulsome praise throughout the banquet."),

    ("choice", "Cloze: Academic Lexis", 4,
     "The archaeologist sought to ________ the chronological order of the stratified pottery shards.",
     ["ascertain", "postulate", "surmise", "hallucinate"],
     "'To ascertain' means to find out or determine definitively with certainty.",
     "Further carbon dating was required to ascertain the exact provenance of the relic."),

    ("choice", "Cloze: Social Registers", 4,
     "The ambassador’s remarks were widely interpreted as a thinly ________ rebuke of the new tariff.",
     ["veiled", "cloaked", "blinded", "muted"],
     "'A thinly veiled rebuke' is a standard high-level collocation meaning barely disguised criticism.",
     "His sarcastic comments were a thinly veiled jab at the department chair."),

    ("choice", "Cloze: Sensory Description", 4,
     "A ________ aroma of freshly roasted Ethiopian coffee wafted through the morning market.",
     ["pungent", "stale", "turbid", "fetid"],
     "'Pungent' describes a sharp, intensely penetrating smell or taste.",
     "The pungent fragrance of wild sage filled the sun-baked hillside."),

    ("choice", "Cloze: Literary Precision", 5,
     "The novelist depicts the bleak moorland with ________ realism and haunting emotional clarity.",
     ["poignant", "lethargic", "indifferent", "banal"],
     "'Poignant' evokes a keen sense of sadness, regret, or deeply felt beauty.",
     "The cellist delivered a poignant rendition of the Elgar concerto."),

    ("choice", "Cloze: Political Discourse", 4,
     "The minister vowed to ________ corruption across all levels of municipal administration.",
     ["eradicate", "perpetuate", "foster", "prolong"],
     "'To eradicate' means to destroy completely or put an end to.",
     "Health organizations mobilized international teams to eradicate the viral contagion."),

    ("choice", "Cloze: Abstract Nouns", 4,
     "She faced the daunting panel of interrogators with unbroken ________ and dignity.",
     ["equanimity", "agitation", "petulance", "haste"],
     "'Equanimity' denotes calm composure, evenness of mind, and poise under strain.",
     "The veteran pilot retained complete equanimity during the engine stall."),

    ("choice", "Cloze: Technical Nuance", 4,
     "Engineers installed dampers to ________ the harmonic resonance caused by gale-force winds.",
     ["mitigate", "compound", "inflame", "aggravate"],
     "'To mitigate' means to make less severe, serious, or painful.",
     "Defensive dunes were constructed along the coast to mitigate hurricane surge risks."),

    ("choice", "Cloze: Rhetorical Precision", 5,
     "The debater exposed the fundamental ________ in his opponent's economic rationale.",
     ["fallacy", "tenet", "axiom", "truism"],
     "'Fallacy' refers to a mistaken belief or a failure in reasoning that renders an argument invalid.",
     "The assumption that higher prices always imply superior craftsmanship is a common fallacy."),

    ("choice", "Cloze: Collocated Modifiers", 4,
     "The archaeological site yielded a ________ trove of Hellenistic gold medallions.",
     ["veritable", "genuine", "literal", "factual"],
     "'A veritable trove' uses the intensifier 'veritable' to emphasize the richness of a metaphor.",
     "The dusty attic proved to be a veritable museum of Edwardian couture."),

    ("choice", "Cloze: Advanced Adverbials", 4,
     "The treaty was ________ ratified by the Senate following days of intense debate.",
     ["duly", "haphazardly", "slackly", "errantly"],
     "'Duly' means in accordance with what is required or appropriate; properly or punctually.",
     "Having inspected the cargo, the port authorities duly issued clearance documentation."),

    ("choice", "Cloze: Contextual Choice", 5,
     "The dictator's regime was characterized by ________ censorship and suppression of dissent.",
     ["draconian", "lenient", "forbearing", "clement"],
     "'Draconian' describes laws or regulations that are excessively harsh and severe.",
     "The government imposed draconian penalties for publishing unauthorized political tracts."),

    ("choice", "Cloze: Nuanced Motion", 4,
     "The solitary figure ________ along the foggy promenade, lost in contemplative melancholy.",
     ["meandered", "careened", "bolted", "hurtled"],
     "'To meander' means to wander leisurely and aimlessly without urgent destination.",
     "The brook meandered through tranquil meadows studded with wild forget-me-nots."),

    ("choice", "Cloze: Scientific Register", 4,
     "The laboratory findings provided ________ evidence that refuted the initial contamination theory.",
     ["conclusive", "tentative", "specious", "vague"],
     "'Conclusive' evidence serves to settle an argument or put an end to all doubt.",
     "Ballistic analysis provided conclusive proof linking the bullet to the recovered weapon."),

    ("choice", "Cloze: Advanced Connectives", 4,
     "The museum houses rare illuminated manuscripts; ________, it curates ancient Byzantine icons.",
     ["moreover", "otherwise", "henceforth", "nonetheless"],
     "'Moreover' is an additive connective used in formal registers to introduce supplementary supporting facts.",
     "The applicant possesses fluent Mandarin; moreover, she has extensive experience in treaty drafting."),

    ("choice", "Cloze: Idiomatic Expressions", 4,
     "The new environmental levy proved to be a bone of ________ between coalition partners.",
     ["contention", "accord", "concord", "compliance"],
     "'A bone of contention' is a subject or issue over which there is continuing disagreement.",
     "The inheritance of the ancestral manor remained a bitter bone of contention between the siblings."),

    ("choice", "Cloze: High Register Adjectives", 5,
     "Her scholarly monograph was lauded for its ________ synthesis of disparate archival records.",
     ["lucid", "opaque", "turgid", "convoluted"],
     "'Lucid' means expressed clearly and easy to understand, especially regarding complex academic topics.",
     "His lucid analysis demystified the intricate derivative contracts for non-specialists."),

    ("choice", "Cloze: Verbal Nuance", 4,
     "The committee resolved to ________ the disciplinary hearing until further affidavits arrived.",
     ["adjourn", "terminate", "obviate", "relinquish"],
     "'To adjourn' means to break off a meeting or legal proceeding with the intention of resuming later.",
     "The magistrate adjourned the session until ten o'clock the following morning."),

    ("choice", "Cloze: Nuanced Attitudes", 4,
     "The conductor cast a ________ look at the violist who arrived late for the dress rehearsal.",
     ["withering", "beaming", "complaisant", "conciliatory"],
     "'A withering look' is a scornful, devastating expression intended to make someone feel ashamed.",
     "She quelled his interruption with a single withering glance across the boardroom."),

    ("choice", "Cloze: Academic Discourse", 5,
     "The sociologist argued that urban decay is inextricably ________ with deindustrialization.",
     ["intertwined", "detached", "unravelled", "severed"],
     "'Inextricably intertwined' describes elements so closely connected that they cannot be separated.",
     "In Venetian history, commerce and maritime supremacy were inextricably intertwined."),

    ("choice", "Cloze: Prepositional Accuracy", 4,
     "The defendant's narrative was totally devoid ________ verifiable corroboration.",
     ["of", "with", "from", "at"],
     "'Devoid' strictly collocates with the preposition 'of' meaning completely lacking.",
     "The barren moonscape was completely devoid of liquid water and plant life."),

    ("choice", "Cloze: Advanced Lexis", 5,
     "The company’s quarterly earnings report served to ________ investor anxieties.",
     ["allay", "exacerbate", "inflame", "ignite"],
     "'To allay' anxieties or fears means to diminish or put them at rest.",
     "The hospital superintendent issued a statement to allay community fears regarding the outbreak."),

    ("choice", "Cloze: Rhetorical Choice", 4,
     "The poet's early death was a ________ loss to the twentieth-century avant-garde movement.",
     ["grievous", "trivial", "negligible", "palpable"],
     "'A grievous loss' describes a loss causing great sorrow, grief, or severe distress.",
     "The fire caused grievous damage to the priceless timber vaulting of the medieval abbey."),

    ("choice", "Cloze: Evaluative Nuance", 4,
     "The magistrate dismissed the plaintiff’s testimony as utterly ________ and ungrounded in fact.",
     ["specious", "credible", "impeccable", "cogent"],
     "'Specious' describes an argument that appears plausible on the surface but is actually deceptive.",
     "He exposed their financial claims as specious rhetoric calculated to deceive auditors."),

    ("choice", "Cloze: Verb Complementation", 4,
     "The general managed to ________ the rebellion before it could spread across the province.",
     ["quash", "succumb", "stumble", "falter"],
     "'To quash' means to suppress or extinguish completely, especially a rebellion or legal ruling.",
     "The Supreme Court moved promptly to quash the unconstitutional municipal statute."),

    ("choice", "Cloze: Precision Phrasing", 4,
     "The historic mansion has fallen into a state of shameful ________ after decades of abandonment.",
     ["disrepair", "conservation", "custody", "tenancy"],
     "'A state of disrepair' is the conventional high-register idiom for structural neglect.",
     "The Victorian botanical glasshouse had fallen into serious disrepair before lottery funding arrived."),

    ("choice", "Cloze: Lexical Subtlety", 5,
     "The critic noted that the protagonist possessed a strangely ________ moral indifference.",
     ["chilling", "warming", "buoyant", "blithe"],
     "'A chilling indifference' conveys a cold, frightening, and disconcerting lack of empathy.",
     "The assassin confessed to his crimes with a chilling lack of emotional remorse.")
]

ADDITIONAL_GRAMMAR = [
    # 85 Advanced C2 Grammar items
    ("Negative Inversion: Scarcely", 4,
     "Scarcely ________ the concert hall when the fire alarm began to wail.",
     ["had we entered", "we had entered", "entered we", "did we enter"],
     "'Scarcely' followed by 'when' requires past perfect subject-auxiliary inversion ('had we entered').",
     "Scarcely had the president concluded his address when the stock market crashed."),

    ("Inversion: Little did", 4,
     "Little ________ that the antique chest contained stolen Renaissance jewels.",
     ["did she realize", "she realized", "she did realize", "had she realized"],
     "Fronted restrictive 'Little' triggers auxiliary inversion ('did she realize').",
     "Little did the explorers suspect that uncharted rapids lay just around the river bend."),

    ("Conditionals: Were it not for", 4,
     "________ your timely financial intervention, our publishing house would have gone bankrupt.",
     ["Were it not for", "Had it not for", "If it were not", "Should it not be"],
     "'Were it not for + noun phrase' expresses a formal hypothetical counterfactual condition.",
     "Were it not for the lighthouse beam, the schooner would have struck the reef."),

    ("Subjunctive: Far be it", 5,
     "Far ________ it from me to criticize your architectural blueprint, but the stairs seem hazardous.",
     ["be", "is", "was", "were"],
     "'Far be it from me' is a formulaic subjunctive expression meaning 'I certainly do not intend to'.",
     "Far be it from me to tell you how to conduct your private research."),

    ("Cleft Sentence: What", 4,
     "________ astounded the jury was the suspect's complete lack of emotional affect.",
     ["What", "It", "That", "Which"],
     "Wh-cleft / pseudo-cleft uses 'What + clause + was/is' to place focus on the clausal predicate.",
     "What irritated the editor most was the reporter's persistent grammatical sloppiness."),

    ("Inversion: Only when", 4,
     "Only when the treaty was signed ________ to celebrate the historic peace accord.",
     ["did the diplomats begin", "the diplomats began", "began the diplomats", "have the diplomats begun"],
     "Fronted 'Only when [clause]' triggers auxiliary inversion in the subsequent matrix clause.",
     "Only when the smoke cleared did rescuers comprehend the full magnitude of the blast."),

    ("Participle Clause: Having", 4,
     "________ twice by fraudulent contractors, the homeowners inspected every invoice with vigilance.",
     ["Having been deceived", "Deceiving", "Having deceived", "Being deceiving"],
     "Perfect passive participle clause ('Having been deceived') denotes an anterior completed experience.",
     "Having been warned repeatedly about identity theft, she shredded all sensitive documents."),

    ("Subjunctive: Mandative verb", 4,
     "The medical ethics panel recommended that the clinical trial ________ suspended immediately.",
     ["be", "is", "was", "must be"],
     "Mandative verbs ('recommend that', 'insist that') govern the base subjunctive verb ('be').",
     "The charter stipulates that each member state contribute proportionally to the peacekeeping budget."),

    ("Inversion: On no account", 4,
     "On no account ________ this door be propped open while the cleanroom is active.",
     ["must", "does", "should it", "ought"],
     "Fronted negative prepositional phrase 'On no account' triggers inversion of modal and subject.",
     "On no account should unsterilized instruments touch surgical trays."),

    ("Inverted Conditional: Had", 5,
     "________ the team known about the severe weather warning, they would never have embarked on the ascent.",
     ["Had", "Were", "Should", "If"],
     "Third conditional inversion replaces 'If the team had known' with 'Had the team known'.",
     "Had the engineers spotted the structural micro-fracture earlier, the catastrophe could have been prevented."),

    ("Inversion: Barely... when", 4,
     "Barely ________ the runway when a flock of birds struck the starboard engine.",
     ["had the jet cleared", "the jet had cleared", "cleared the jet", "did the jet clear"],
     "'Barely... when' requires past perfect inversion in the fronted clause.",
     "Barely had the ambassador stepped out of his limousine when journalists mobbed him."),

    ("Adverb Fronting: Exhausted though", 4,
     "________ though they were after the mountain trek, the rescue team refused to halt.",
     ["Exhausted", "Exhausting", "Being exhausted", "Having exhausted"],
     "Adjective + though/as + subject + verb creates an emphatic concessive clause.",
     "Poor though he was, the philosopher refused to accept royal patronage."),

    ("Inversion: Nowhere", 4,
     "Nowhere ________ such magnificent displays of Byzantine architecture outside Constantinople.",
     ["will you encounter", "you will encounter", "you encounter", "encounter you"],
     "Fronted negative location adverb 'Nowhere' requires auxiliary inversion.",
     "Nowhere have I experienced such gracious hospitality as during my travels through Oman."),

    ("Formulaic Subjunctive: Suffice", 4,
     "Suffice it to ________ that our quarterly projections were fully vindicated by the market.",
     ["say", "said", "says", "saying"],
     "'Suffice it to say' is a fixed formulaic subjunctive meaning 'it is enough to say'.",
     "Suffice it to say that negotiations concluded amicably despite fierce opening stances."),

    ("Inversion: No sooner", 4,
     "No sooner ________ into the warm bath than the telephone rang incessantly.",
     ["had she stepped", "she had stepped", "did she step", "stepped she"],
     "'No sooner... than' mandates past perfect inversion.",
     "No sooner had the keynote speaker taken the podium than the power failed."),

    ("Double Comparative", 3,
     "The more intricate the theoretical framework, ________ it becomes to test empirically.",
     ["the more difficult", "more difficult", "the difficulty", "the most difficult"],
     "Correlative comparative construction uses 'The [comparative]..., the [comparative]...'.",
     "The higher the altitude of the vineyard, the slower the grapes ripen."),

    ("Fronted Participle: Deprived", 4,
     "________ of oxygen at extreme altitudes, climbers often experience cognitive disorientation.",
     ["Deprived", "Depriving", "Having deprived", "Being deprived to"],
     "Past participle phrase functioning as a causal adverbial modifier to the main subject.",
     "Deprived of sunlight during the polar winter, residents rely on full-spectrum lamps."),

    ("Subjunctive: Be that as it may", 4,
     "Be that ________ it may, regulatory compliance cannot be waived under any circumstances.",
     ["as", "so", "like", "how"],
     "'Be that as it may' is a formulaic concessive subjunctive meaning 'nevertheless'.",
     "Be that as it may, we must abide by the arbitrator's legally binding decree."),

    ("Inversion: Under no circumstances", 4,
     "Under no circumstances ________ disclose the client's financial details to press representatives.",
     ["may you", "you may", "you can", "can you the"],
     "Fronted restrictive phrase triggers modal-subject inversion.",
     "Under no circumstances should flammable liquids be stored near the boiler room."),

    ("Ellipsis: When in Rome", 3,
     "When ________ with insurmountable challenges, exceptional leaders demonstrate creative poise.",
     ["faced", "facing", "having faced", "to face"],
     "Reduced adverbial time clause with ellipsis of subject and auxiliary ('When [they are] faced').",
     "When confronted with contradictory eyewitness testimonies, the investigator re-examined physical forensic evidence."),

    ("Modal Deduction: Must have", 4,
     "The floor was soaking wet; the storm water ________ through the broken skylight during the deluge.",
     ["must have seeped", "should have seeped", "would have seeped", "could seep"],
     "'Must have + past participle' expresses logical past certainty based on compelling physical evidence.",
     "The footprints were fresh; the intruder must have fled only moments before our arrival."),

    ("Inversion: Seldom", 3,
     "Seldom ________ such unanimous consensus among member states at the plenary summit.",
     ["has there been", "there has been", "is there", "was there been"],
     "Fronted frequency adverb 'Seldom' triggers subject-auxiliary inversion.",
     "Seldom does an artist achieve both critical acclaim and commercial supremacy in equal measure."),

    ("Mixed Conditional: Type 3 to Type 2", 5,
     "If the treaty ________ signed last year, European borders would be open to free transit today.",
     ["had been", "were", "would have been", "would be"],
     "Past counterfactual condition ('had been') having a present enduring consequence ('would be open today').",
     "If she had taken the antidote promptly, she would not be in intensive care now."),

    ("Inversion: Only after", 4,
     "Only after the DNA samples were verified ________ the chief suspect.",
     ["did the detective arrest", "the detective arrested", "arrested the detective", "had the detective arrested"],
     "Fronted 'Only after + clause' requires inversion in the main clause.",
     "Only after the auditor audited the ledgers did the director realize funds had been embezzled."),

    ("Subjunctive: Wish with Were", 3,
     "I wish our team ________ more attentive to small details during the design sprint.",
     ["were", "was to be", "has been", "is"],
     "Formal subjunctive 'were' after 'wish' expressing present/hypothetical unreality.",
     "I wish it were possible to retain this historic facade while retrofitting the interior."),

    ("Cleft Sentence: It was", 4,
     "It was precisely through her stubborn perseverance ________ the breakthrough was achieved.",
     ["that", "which", "how", "where"],
     "It-cleft focusing on a prepositional adverbial phrase requires the complementizer 'that'.",
     "It was with deep reluctance that the prime minister announced the curfew."),

    ("Absolute Clause", 5,
     "All options ________, the board voted unanimously to commence liquidation proceedings.",
     ["having been exhausted", "exhausting", "have been exhausted", "exhausted having"],
     "Absolute nominative clause containing a participle phrase independent of the main sentence subject.",
     "Her dissertation finally completed, Elena celebrated with a week in the Scottish Highlands."),

    ("Inversion: Not until", 4,
     "Not until the dawn broke ________ the full catastrophe wrought by the tsunami.",
     ["did rescuers witness", "rescuers witnessed", "witnessed rescuers", "had rescuers witnessed"],
     "Fronted 'Not until [time]' triggers auxiliary inversion in the subsequent independent clause.",
     "Not until the final whistle blew did the supporters erupt into ecstatic song."),

    ("Negative Concord Avoidance", 4,
     "Hardly ________ anyone in the auditorium dared to challenge the speaker's controversial thesis.",
     ["a soul", "nobody", "no one", "not anyone"],
     "'Hardly' carries negative force and cannot collocate with negative pronouns like 'nobody'.",
     "Hardly a leaf stirred in the suffocating stillness before the thunderstorm."),

    ("Inversion: So + Adjective", 5,
     "So ________ was the demand for tickets that the server crashed within three seconds.",
     ["overwhelming", "overwhelmed", "overwhelmingly", "overwhelm"],
     "Fronted 'So + adjective + was + subject + that...' is an emphatic inverted result structure.",
     "So acute was his hearing that he could detect the flutter of a moth's wings.")
]

ADDITIONAL_CONFUSABLES = [
    # 45 High C2 Confusable Word Pairs & Nuances
    ("Complaisant vs Complacent", 5,
     "He was far too ________ to dispute the exorbitant fees charged by the consultants.",
     ["complaisant", "complacent", "compliant", "complaisance"],
     "'Complaisant' means willing to please others or acquiescent. 'Complacent' means smugly self-satisfied.",
     "A complaisant subordinate rarely challenges the questionable decisions of management."),

    ("Ingenuous vs Ingenious", 4,
     "The architect conceived an ________ ventilation mechanism that reduced air conditioning expenses.",
     ["ingenious", "ingenuous", "ingenuity", "ingenuously"],
     "'Ingenious' means clever, original, and inventive. 'Ingenuous' means innocent, naive, and unsuspecting.",
     "Her ingenious patent for water filtration won an international design award."),

    ("Continuous vs Continual", 4,
     "The committee was plagued by ________ interruptions from demonstrators outside the hall.",
     ["continual", "continuous", "continuance", "continuity"],
     "'Continual' means recurring frequently at intervals. 'Continuous' means uninterrupted without cessation.",
     "Continual arguments between the partners eventually paralyzed the firm."),

    ("Presumptive vs Presumptuous", 5,
     "It was remarkably ________ of the intern to contradict the managing partner during the pitch.",
     ["presumptuous", "presumptive", "presumed", "presuming"],
     "'Presumptuous' means failing to observe boundaries of what is appropriate; overbold and arrogant.",
     "She considered it presumptuous of him to ask about her personal inheritance."),

    ("Alternate vs Alternative", 4,
     "The board devised an ________ strategy in case regulatory approval was denied.",
     ["alternative", "alternate", "alternating", "alternation"],
     "'Alternative' means available as another possibility. 'Alternate' means occurring in turns; every other.",
     "Solar power offers a viable alternative to hydrocarbon combustion."),

    ("Decided vs Decisive", 4,
     "The general’s flank counterattack proved to be the ________ blow that ended the siege.",
     ["decisive", "decided", "decisiveness", "deciding"],
     "'Decisive' means producing a definitive result or resolution. 'Decided' means clear, definite, or unmistakable.",
     "A decisive military victory compelled the rebel leaders to sign the ceasefire."),

    ("Adverse vs Averse", 4,
     "The fund manager was deeply ________ to investing in volatile unbacked cryptocurrencies.",
     ["averse", "adverse", "aversive", "adversity"],
     "'Averse' means having a strong dislike of or opposition to something (usually 'averse to').",
     "He was not averse to taking calculated financial risks when the payoff was substantial."),

    ("Affect vs Effect", 3,
     "The new corporate restructuring will ________ major changes across the supply chain.",
     ["effect", "affect", "effectuate", "affective"],
     "'To effect' (verb) means to bring about or accomplish. 'To affect' means to influence or modify.",
     "The incoming administration pledged to effect comprehensive health care reforms."),

    ("Appraise vs Apprise", 4,
     "The foreign secretary immediately ________ the prime minister of the diplomatic breakdown.",
     ["apprised", "appraised", "apprizing", "appraiser"],
     "'To apprise' means to inform or notify someone. 'To appraise' means to assess value or quality.",
     "Please keep me apprised of any unexpected developments during the summit."),

    ("Censure vs Censor", 4,
     "The ethics committee voted to publicly ________ the parliamentarian for financial misconduct.",
     ["censure", "censor", "censurement", "census"],
     "'To censure' means to express severe disapproval of someone in a formal statement. 'To censor' is to suppress.",
     "The physician faced severe censure from the medical licensing council."),

    ("Disinterested vs Uninterested", 4,
     "The disputed maritime boundary was mediated by a ________ international arbitrator.",
     ["disinterested", "uninterested", "disinteresting", "uninterest"],
     "'Disinterested' means impartial and unbiased. 'Uninterested' means not interested, bored, or indifferent.",
     "A judge must remain completely disinterested throughout the trial proceedings."),

    ("Flaunt vs Flout", 4,
     "The shipping corporation continued to ________ maritime safety protocols despite stern warnings.",
     ["flout", "flaunt", "flouting", "flaunting"],
     "'To flout' means to openly disregard a rule or law. 'To flaunt' means to display ostentatiously.",
     "Speeding motorists brazenly flout the legal limits on residential streets."),

    ("Historic vs Historical", 3,
     "The fall of the Berlin Wall was a ________ milestone that reshaped modern European politics.",
     ["historic", "historical", "historicity", "historian"],
     "'Historic' means momentous and famous in history. 'Historical' means belonging or pertaining to the past.",
     "The signing of the Magna Carta was a truly historic occasion."),

    ("Tortuous vs Torturous", 5,
     "The alpine highway took a ________ path through jagged limestone gorges.",
     ["tortuous", "torturous", "tortured", "torture"],
     "'Tortuous' means full of twists, turns, or complex windings. 'Torturous' means causing severe physical/mental pain.",
     "Negotiators endured a tortuous series of midnight diplomacy sessions."),

    ("Venal vs Venial", 5,
     "The investigative journalist exposed a ring of ________ customs officials taking port bribes.",
     ["venal", "venial", "venality", "venially"],
     "'Venal' means corrupt and susceptible to bribery. 'Venial' denotes a minor, forgivable fault.",
     "A venal judiciary destroys public trust in the rule of law."),

    ("Judicial vs Judicious", 4,
     "The treasurer exercised ________ caution when investing municipal endowment funds.",
     ["judicious", "judicial", "judiciary", "judging"],
     "'Judicious' means having or showing good judgment and sensible prudence. 'Judicial' relates to judges/courts.",
     "A judicious allocation of capital prevented the company from suffering liquidity strain."),

    ("Official vs Officious", 4,
     "The queue was held up by an ________ bureaucrat demanding redundant travel stamps.",
     ["officious", "official", "officiously", "officiousness"],
     "'Officious' means assertively domineering in an intrusively petty manner. 'Official' relates to authority.",
     "We were irritated by the officious usher who insisted on checking our tickets four times."),

    ("Perquisite vs Prerequisite", 4,
     "Proficiency in written English is a mandatory ________ for enrolling in the doctoral program.",
     ["prerequisite", "perquisite", "requisite", "perk"],
     "'Prerequisite' is a thing required as a prior condition. 'Perquisite' (perk) is a special benefit or privilege.",
     "A bachelor's degree is a prerequisite for entry into the civil service."),

    ("Restive vs Restful", 4,
     "The crowd grew increasingly ________ as the delayed train failed to arrive.",
     ["restive", "restful", "restingly", "restlessness"],
     "'Restive' means restless, impatient, or difficult to control. 'Restful' means peaceful and soothing.",
     "The horses grew restive during the thunderous lightning storm."),

    ("Precipitous vs Precipitate", 5,
     "The government's ________ withdrawal of fuel subsidies sparked widespread street strikes.",
     ["precipitate", "precipitous", "precipitation", "precipitously"],
     "'Precipitate' (adjective) means done hastily, impulsively, or without deliberation. 'Precipitous' means steep.",
     "It would be precipitate to dismiss the lead detective before reviewing all ballistics."),

    ("Sanguine vs Sanguinary", 5,
     "Despite grim quarterly returns, the chief executive remained remarkably ________ about recovery.",
     ["sanguine", "sanguinary", "sanguineness", "sanguinely"],
     "'Sanguine' means optimistic or positive, especially in bad situations. 'Sanguinary' means involving much bloodshed.",
     "Economists were not sanguine about the prospect of curbing runaway inflation."),

    ("Proscribe vs Prescribe", 4,
     "International environmental treaties strictly ________ the dumping of toxic radioactive slurry.",
     ["proscribe", "prescribe", "proscription", "prescription"],
     "'To proscribe' means to forbid, ban, or outlaw by decree. 'To prescribe' means to authorize or recommend.",
     "The penal code proscribes all forms of insider trading on securities exchanges."),

    ("Deprecate vs Depreciate", 4,
     "The purist professor was quick to ________ modern slang in formal academic dissertations.",
     ["deprecate", "depreciate", "deprecatory", "depreciation"],
     "'To deprecate' means to express vehement disapproval of. 'To depreciate' means to diminish in value.",
     "She deprecated the shallow celebrity culture that dominated prime-time television."),

    ("Flounder vs Founder", 5,
     "Without reliable venture capital, the promising biotechnology startup began to ________.",
     ["founder", "flounder", "foundered", "floundered"],
     "'To founder' means to sink, fail completely, or collapse. 'To flounder' means to struggle clumsily.",
     "The peace talks foundered over contested territorial rights along the disputed river."),

    ("Enervate vs Energize", 5,
     "The suffocating equatorial humidity seemed to ________ the research team within an hour.",
     ["enervate", "energize", "enervation", "enervatingly"],
     "'To enervate' means to drain of energy or vitality; weaken. It is the opposite of energize.",
     "A protracted bout of dengue fever thoroughly enervated the seasoned explorer.")
]

ADDITIONAL_VOCAB = [
    # 15 High C2 Vocabulary items
    ("trenchant", 5, "His ________ critiques of post-war architectural brutalism reshaped urban design standards.",
     ["trenchant", "bland", "equivocal", "feeble"],
     "'Trenchant' means incisive, vigorous, and keenly articulate in expression or style.",
     "The editorial delivered a trenchant indictment of parliamentary sleaze."),

    ("insouciance", 4, "She faced the terrifying cross-examination with an air of breezy ________.",
     ["insouciance", "trepidation", "dismay", "anxiety"],
     "'Insouciance' is a state of casual lack of concern or carefree nonchalance.",
     "His aristocratic insouciance irritated the solemn bank auditors."),

    ("recondite", 5, "The professor was famed for his treatises on ________ aspects of medieval canon law.",
     ["recondite", "pedestrian", "accessible", "lucid"],
     "'Recondite' describes knowledge that is abstruse, little known, and obscure.",
     "The seminar focused on recondite Byzantine legal disputes that few scholars comprehended."),

    ("supercilious", 4, "The clerk dismissed the applicant's inquiries with a ________ curl of his lip.",
     ["supercilious", "deferential", "modest", "ingratiating"],
     "'Supercilious' means behaving as though one thinks one is superior to others; arrogant.",
     "Her supercilious condescension alienated her junior colleagues on the editorial desk."),

    ("obsequious", 4, "The court was populated by ________ sycophants competing for the monarch's favor.",
     ["obsequious", "insolent", "defiant", "pugnacious"],
     "'Obsequious' means obedient or attentive to an excessive or servile degree.",
     "The head waiter offered an obsequious bow as the foreign dignitaries entered."),

    ("truculent", 5, "The suspect adopted an openly ________ attitude when questioned about his financial assets.",
     ["truculent", "conciliatory", "docile", "genial"],
     "'Truculent' means eager or quick to argue or fight; aggressively defiant.",
     "The truculent demeanor of the striker provoked the opposing defender into a red card."),

    ("lachrymose", 5, "The play was criticized as a ________ melodrama designed to extract cheap tears.",
     ["lachrymose", "hilarious", "jubilant", "ebullient"],
     "'Lachrymose' means tearful, prone to weeping, or mournful in tone.",
     "Her lachrymose speeches at the memorial failed to conceal her past hostility."),

    ("pusillanimous", 5, "The cabinet was lambasted for its ________ surrender to corporate lobbyist demands.",
     ["pusillanimous", "valiant", "intrepid", "audacious"],
     "'Pusillanimous' means showing a lack of courage or determination; timid.",
     "The military leadership criticized the government's pusillanimous retreat from the frontier."),

    ("proclivity", 4, "From an early age, the young polymath demonstrated a natural ________ for mathematics.",
     ["proclivity", "aversion", "disinclination", "reluctance"],
     "'Proclivity' means a tendency to choose or do something regularly; an inclination or predisposition.",
     "His well-documented proclivity for luxury cars eventually led to his insolvency."),

    ("ebullient", 4, "The director was in an ________ mood following the glowing opening-night reviews.",
     ["ebullient", "morose", "crestfallen", "despondent"],
     "'Ebullient' means cheerful and full of energy; exuberant.",
     "An ebullient crowd greeted the victorious Olympic gymnasts at the municipal airport.")
]

ADDITIONAL_COLLOC = [
    # 15 High C2 Collocations
    ("curry favor", 4, "The sycophantic aide did everything possible to ________ favor with the prime minister.",
     ["curry", "seek", "procure", "solicit"],
     "'To curry favor' is a fixed idiom meaning to ingratiate oneself through flattery or servile behavior.",
     "Junior partners often curry favor with the senior partner by volunteering for weekend shifts."),

    ("wreak havoc", 4, "Tropical storm winds threatened to ________ havoc on the island's citrus orchards.",
     ["wreak", "inflict", "cause", "make"],
     "'To wreak havoc' is the canonical collocation meaning to cause immense damage or chaos.",
     "Uncontrolled flash floods wreaked havoc across the river delta."),

    ("broach the subject", 4, "She was extremely anxious about how to ________ the subject of a salary increase.",
     ["broach", "breach", "launch", "pierce"],
     "'To broach the subject' means to introduce or raise a sensitive topic for discussion.",
     "He waited until after dinner to broach the delicate matter of their inheritance."),

    ("stem the tide", 4, "Emergency monetary tightening was implemented to ________ the tide of currency depreciation.",
     ["stem", "stop", "halt", "check"],
     "'To stem the tide' means to stop something adverse from continuing to expand or develop.",
     "Constructing seawalls was insufficient to stem the tide of coastal erosion."),

    ("cast doubt", 4, "The forensic inconsistencies served to ________ serious doubt upon the prosecution's timeline.",
     ["cast", "throw", "shed", "lay"],
     "'To cast doubt' means to cause something to be questioned or appear dubious.",
     "New astronomical measurements cast doubt on the previously accepted age of the star cluster."),

    ("reap the benefits", 4, "Having invested heavily in renewable research, the company is now set to ________ the benefits.",
     ["reap", "harvest", "gather", "seize"],
     "'To reap the benefits/rewards' means to enjoy the positive consequences of past efforts.",
     "Those who exercise consistently throughout youth reap the benefits in their senior years."),

    ("herald a new era", 5, "The commercialization of quantum computing will ________ a new era of cryptography.",
     ["herald", "portend", "foretell", "proclaim"],
     "'To herald a new era' means to be a sign that a new epoch or innovation is beginning.",
     "The launch of the orbital telescope heralded a new era of cosmic exploration."),

    ("whet the appetite", 4, "The tantalizing film teaser did much to ________ the appetite of cinema audiences.",
     ["whet", "wet", "sharpen", "stir"],
     "'To whet one's appetite' means to stimulate a desire or interest for something.",
     "The tasting menu's first course served to whet our appetite for the gourmet meal that followed."),

    ("glean information", 4, "Diplomats managed to ________ valuable information from the intercepted diplomatic cables.",
     ["glean", "reap", "harvest", "scavenge"],
     "'To glean information' means to collect information gradually from various sources with difficulty.",
     "From offhand remarks made at the conference, the reporter gleaned that a merger was pending."),

    ("pay lip service", 4, "Corporate leaders often pay ________ service to green initiatives without reducing emissions.",
     ["lip", "mouth", "tongue", "voice"],
     "'To pay lip service' means to express approval of or support for something insincerely.",
     "They paid lip service to workplace equality, but senior promotions remained exclusively male.")
]

ADDITIONAL_PHRASAL = [
    # 15 High C2 Phrasal Verbs
    ("stave off", 4, "The central bank raised interest rates aggressively to ________ off catastrophic inflation.",
     ["stave", "ward", "fend", "hold"],
     "'To stave off' means to avert, delay, or ward off something undesirable or catastrophic.",
     "She drank herbal infusion and rested to stave off the onset of flu symptoms."),

    ("flesh out", 4, "The draft proposal was promising, but the consultant needed to ________ out the financial specifics.",
     ["flesh", "beef", "pad", "fill"],
     "'To flesh out' means to add more details, depth, or substance to a skeleton plan or design.",
     "The novelist spent six months fleshing out the backstories of the minor characters."),

    ("iron out", 4, "Legal delegates held an all-night summit to ________ out discrepancies in the bilateral accord.",
     ["iron", "smooth", "hammer", "straighten"],
     "'To iron out' means to resolve minor difficulties, misunderstandings, or inconsistencies.",
     "We met over lunch to iron out the remaining contractual details."),

    ("shore up", 4, "The finance ministry injected billions into the treasury to ________ up public confidence.",
     ["shore", "brace", "prop", "buttress"],
     "'To shore up' means to support, strengthen, or reinforce a weak or failing position.",
     "Emergency tariffs were instituted to shore up the struggling domestic steel sector."),

    ("chalk up to", 4, "The fledgling director ________ up the lukewarm reviews to audience misunderstanding.",
     ["chalked", "put", "pinned", "ascribed"],
     "'To chalk up to' means to explain something by stating that it was caused by a specific factor.",
     "We chalked the technical glitch up to teething troubles in the new software."),

    ("play down", 4, "Spokespersons sought to ________ down the severity of the structural pipeline fissure.",
     ["play", "soften", "damp", "tone"],
     "'To play down' means to make something appear less serious, important, or alarming than it actually is.",
     "The foreign office tried to play down the rift between the two prime ministers."),

    ("zero in on", 4, "During cross-examination, the attorney managed to ________ in on the defendant's flawed timeline.",
     ["zero", "home", "focus", "target"],
     "'To zero in on' means to direct all attention or effort specifically towards an exact point.",
     "Radar technicians zeroed in on the faint distress signal originating from the valley."),

    ("gloss over", 4, "The annual report attempted to ________ over significant losses incurred by the retail branch.",
     ["gloss", "smooth", "brush", "paper"],
     "'To gloss over' means to treat an unpleasant or embarrassing fact lightly, concealing flaws.",
     "He tended to gloss over his previous business failures when pitching to venture capitalists."),

    ("hammer out", 4, "After twenty-four hours of round-the-clock talks, the unions ________ out a wage settlement.",
     ["hammered", "thrashed", "pounded", "forged"],
     "'To hammer out' means to arrive at an agreement or solution through vigorous negotiation.",
     "Diplomats finally hammered out the language of the cease-fire agreement."),

    ("mull over", 4, "She asked for forty-eight hours to ________ over the prestigious offer from Oxford.",
     ["mull", "chew", "pore", "ponder"],
     "'To mull over' means to think deeply and carefully about a proposal or decision over time.",
     "The magistrate took his time to mull over the defense attorney's constitutional objection.")
]
