# scripts/data_definitions.py
# Rich C2 Question definitions to expand bank to ~1,010 unique items

NEW_VOCAB = [
    ("Acquiesce", 3, "After months of negotiations, the minority shareholders reluctantly decided to ________ to the takeover terms.",
     ["acquiesce", "repudiate", "dissent", "abnegate"],
     "'Acquiesce' means to accept something reluctantly but without protest.",
     "The board had no choice but to acquiesce in the demands of the regulatory committee."),
    ("Circumspect", 3, "Diplomatic envoys must remain ________ when discussing sensitive cross-border territorial concessions.",
     ["circumspect", "reckless", "rash", "audacious"],
     "'Circumspect' means wary, unwilling to take risks, and prudent in conduct.",
     "A circumspect approach is advisable when entering unfamiliar foreign markets."),
    ("Dissemble", 4, "An experienced poker player learns to ________ their true emotions behind an inscrutable expression.",
     ["dissemble", "reveal", "manifest", "proclaim"],
     "'Dissemble' means to conceal one's true motives, feelings, or beliefs.",
     "He was accused of dissembling when questioned about his private business dealings."),
    ("Equivocal", 3, "The auditor's report was frustratingly ________, offering no definitive verdict on the firm's solvency.",
     ["equivocal", "lucid", "unambiguous", "explicit"],
     "'Equivocal' means open to more than one interpretation; ambiguous or uncertain.",
     "The minister gave an equivocal response regarding potential tax increases."),
    ("Glib", 3, "Voters were weary of ________ promises delivered by politicians who had never visited their rural townships.",
     ["glib", "profound", "cogent", "heartfelt"],
     "'Glib' describes words or speakers that are fluent and voluble but insincere and shallow.",
     "She saw through his glib compliments and demanded concrete fiscal commitments."),
    ("Inured", 4, "Living in the Arctic had ________ the expedition members to sub-zero blizzards and perpetual darkness.",
     ["inured", "sensitized", "vulnerable", "averse"],
     "'Inured' means accustomed to something undesirable, especially through prolonged exposure.",
     "Emergency room surgeons gradually become inured to traumatic visual distress."),
    ("Limpid", 5, "The brook's ________ waters allowed hikers to admire smooth quartz pebbles resting on the stream bed.",
     ["limpid", "turbid", "murky", "viscous"],
     "'Limpid' means completely clear, pellucid, and transparent.",
     "His prose was admired for its limpid lucidity and absence of jargon."),
    ("Nadir", 4, "The collapse of the municipal bank marked the absolute ________ of the province's post-war economic depression.",
     ["nadir", "zenith", "apotheosis", "apex"],
     "'Nadir' denotes the lowest point in the fortunes of a person or organization (opposite of zenith).",
     "Her career reached its nadir after the disastrous failure of her second novel."),
    ("Ostensible", 4, "The ________ reason for the minister's voyage was cultural exchange, but trade negotiations dominated the agenda.",
     ["ostensible", "genuine", "authentic", "substantive"],
     "'Ostensible' means stated or appearing to be true, but not necessarily so.",
     "Their ostensible friendliness masked intense corporate rivalry."),
    ("Panoply", 5, "The state banquet showcased an impressive ________ of traditional tapestries, gold plate, and ceremonial heraldry.",
     ["panoply", "dearth", "paucity", "modesty"],
     "A 'panoply' is an extensive, splendid, or impressive collection or display.",
     "The exhibition displayed a dazzling panoply of Renaissance armor."),
    ("Quiescent", 4, "The volcano had remained ________ for over three centuries before roaring back to life with a violent eruption.",
     ["quiescent", "eruptive", "volatile", "turbulent"],
     "'Quiescent' means in a state or period of dormancy, inactivity, or rest.",
     "Tensions between the two factions remained quiescent until the election campaign began."),
    ("Ruminate", 3, "Philosophers have gathered for millennia to ________ upon the ethical implications of human mortality.",
     ["ruminate", "disregard", "skim", "glance"],
     "'To ruminate' means to think deeply or meditate at length about something.",
     "He spent days ruminating on the career dilemma before tendering his resignation."),
    ("Sycophancy", 4, "The monarch surrounded himself with fawning courtiers whose unceasing ________ distorted his political judgment.",
     ["sycophancy", "insolence", "candor", "impertinence"],
     "'Sycophancy' is servile, fawning behavior toward someone important in order to gain advantage.",
     "Integrity requires telling difficult truths rather than resorting to convenient sycophancy."),
    ("Tenable", 3, "In light of newly discovered archaeological evidence, the traditional chronology is no longer ________.",
     ["tenable", "flawed", "specious", "spurious"],
     "'Tenable' means able to be maintained or defended against attack or objection.",
     "His defensive legal position proved scarcely tenable under vigorous cross-examination."),
    ("Urbane", 4, "The ambassador was renowned for his ________ manners, charm, and effortless wit at diplomatic functions.",
     ["urbane", "boorish", "churlish", "uncouth"],
     "'Urbane' describes a person who is courteous, refined, and sophisticated in manner.",
     "An urbane host, he ensured every overseas visitor was welcomed cordially."),
    ("Velleity", 5, "His desire to write a historical monograph remained a mere ________, never translating into dedicated research.",
     ["velleity", "obsession", "compulsion", "resolve"],
     "'Velleity' is a wish or inclination so slight that it does not lead to the slightest action.",
     "She had a velleity toward foreign travel, but rarely ventured beyond her home county.")
]

print("Loaded NEW_VOCAB definitions.")
