# scripts/data_definitions_expansion.py
# Additions for Collocations, Phrasals, Cloze/Transformations, Grammar, and Confusables

NEW_COLLOC = [
    ("Prepositional Phrases", 2, "The ambassador addressed the delegates ________ behalf of the prime minister.",
     ["on", "in", "at", "for"],
     "'On behalf of' means as a representative of or in the interest of someone.",
     "She accepted the honorary degree on behalf of her late father."),
    ("Prepositional Phrases", 2, "Due to bad weather, the match was postponed ________ further notice.",
     ["until", "for", "to", "by"],
     "'Until further notice' means until a new announcement or instruction is made.",
     "The municipal library will remain closed until further notice."),
    ("Idiomatic Verbs", 3, "The executive tried to ________ the blame onto junior analysts for the spreadsheet error.",
     ["shift", "turn", "cast", "shed"],
     "'To shift the blame onto someone' means to transfer responsibility or fault to another person.",
     "Rather than accepting oversight, leadership attempted to shift the blame onto subcontractors."),
    ("Adjective + Noun Collocations", 3, "There is a ________ chance that the central bank will raise interest rates this quarter.",
     ["slim", "thin", "lean", "narrow"],
     "'A slim chance' (or slight chance) is the established collocation for very low probability.",
     "Doctors warned there was only a slim chance of full neurological recovery."),
    ("Verb + Noun Collocations", 3, "You must ________ your best to finish the dissertation before the deadline.",
     ["do", "make", "put", "give"],
     "The fixed collocation is 'to do one's best', not 'make one's best'.",
     "She promised to do her best to represent the client's interests in court."),
    ("Adverb + Adjective Collocations", 4, "The two accounts of the accident were ________ contradictory.",
     ["diametrically", "pointedly", "drastically", "heavily"],
     "'Diametrically opposed' or 'diametrically contradictory' means completely and utterly contrary.",
     "The witnesses provided diametrically contradictory timelines of the suspect's movements."),
    ("Idiomatic Metaphors", 4, "The surprise inspection caught the warehouse staff on the ________.",
     ["hop", "run", "jump", "fly"],
     "'To catch someone on the hop' is a British idiom meaning to catch someone unprepared.",
     "The unexpected resignation of the finance director caught the board on the hop."),
    ("Idiomatic Expressions", 4, "She has an old head on young ________, displaying wisdom well beyond her years.",
     ["shoulders", "arms", "hands", "knees"],
     "'An old head on young shoulders' describes a young person who exhibits mature judgment.",
     "At only eighteen, the young entrepreneur showed an old head on young shoulders during negotiations."),
    ("Literary Binomials", 5, "The solitary watchman spent the night in the ________ and quiet of the snowbound chapel.",
     ["peace", "rest", "calm", "ease"],
     "'Peace and quiet' is a classic irreversible binomial meaning tranquil calm.",
     "After months in the bustling capital, she longed for the peace and quiet of the countryside."),
    ("Prepositional Idioms", 5, "His controversial editorial was written in ________ with two foreign correspondents.",
     ["collaboration", "collision", "connivance", "concurrence"],
     "'In collaboration with' is the formal collocation for joint cooperative endeavor.",
     "The monograph was written in collaboration with leading archival scholars in Leipzig."),
    ("Verb + Noun Idioms", 4, "We must ________ amends for the unintended damage caused by the excavation crew.",
     ["make", "do", "render", "give"],
     "The standard fixed idiom is 'to make amends (for something)', meaning to compensate or rectify.",
     "He sent a handwritten letter of apology to make amends for his thoughtless remark."),
    ("Prepositional Phrases", 3, "The agreement was signed in ________ of three certified notaries.",
     ["presence", "company", "sight", "view"],
     "'In the presence of' is the formal legal phrase required when witnessing signatures.",
     "The contract must be ratified in the presence of an independent solicitor."),
    ("Idioms of Uncertainty", 4, "With election polls neck and neck, the referendum outcome is on a ________ edge.",
     ["knife", "razor", "blade", "sword"],
     "'On a knife edge' describes an extremely precarious, tense, or uncertain situation.",
     "The company's commercial survival teetered on a knife edge until emergency financing was approved."),
    ("Idioms of Secrecy", 4, "The preliminary peace talks were held ________ closed doors in a secluded Swiss chalet.",
     ["behind", "under", "inside", "within"],
     "'Behind closed doors' means in private, confidential secrecy without public scrutiny.",
     "Crucial budgetary concessions were hammered out behind closed doors late into the night."),
    ("Adjective + Noun Collocations", 5, "The committee reached a ________ conclusion after reviewing four years of data.",
     ["unanimous", "equable", "homogenous", "uniform"],
     "'A unanimous conclusion' indicates complete and undivided consensus among all voters.",
     "The jury arrived at a unanimous conclusion after only two hours of deliberation."),
    ("Idiomatic Expressions", 4, "The sudden collapse of our primary supplier pulled the ________ from under our feet.",
     ["rug", "carpet", "mat", "floor"],
     "'To pull the rug from under someone's feet' means to abruptly withdraw vital support or stability.",
     "Canceling the municipal research grant pulled the rug from under the laboratory's team."),
    ("Verb + Idiom Collocations", 5, "I will not ________ hands with individuals who profit from illegal timber trafficking.",
     ["shake", "join", "hold", "cross"],
     "'To shake hands with someone' represents entering friendly or formal association.",
     "The prime minister refused to shake hands with the corrupt regional warlord."),
    ("Prepositional Idioms", 3, "Her promotion came as no surprise; she has long been in the director's good ________.",
     ["books", "graces", "favors", "regards"],
     "'In someone's good books' is the idiomatic phrase meaning in someone's favor or high regard.",
     "Diligent interns always endeavor to stay in the senior partner's good books."),
    ("Idioms of Extent", 4, "The fire destroyed the historic estate to all intents and ________.",
     ["purposes", "meanings", "reasons", "aims"],
     "'To all intents and purposes' means practically speaking; in all significant respects.",
     "Without its international license, the airline was to all intents and purposes bankrupt."),
    ("Idioms of Directness", 3, "He got straight to the ________, demanding to know where the missing funds had gone.",
     ["point", "fact", "core", "mark"],
     "'To get straight to the point' means to address the core subject immediately without digression.",
     "Let us skip the pleasantries and get straight to the point of today's meeting."),
    ("Prepositional Phrases", 4, "The defendant was released on bail ________ condition that she surrender her passport.",
     ["on", "under", "in", "with"],
     "'On condition that' is the precise formal conjunction phrase expressing a stipulated prerequisite.",
     "He was granted permission to leave camp on condition that he return before sunset."),
    ("Idiomatic Pairs", 4, "Through all the trials of life, she remained the life and ________ of the party.",
     ["soul", "spirit", "heart", "breath"],
     "'The life and soul of the party' (US: 'life of the party') denotes an energetic, vibrant person.",
     "His infectious laugh always made him the life and soul of our university reunions."),
    ("Prepositional Phrases", 4, "The legislation was introduced ________ a view to curtailing industrial groundwater pollution.",
     ["with", "in", "to", "for"],
     "'With a view to + -ing' is the formal structure meaning with the intention or purpose of doing something.",
     "They renovated the historic farmhouse with a view to converting it into a boutique hotel."),
    ("Idioms of Comparison", 3, "Compared to the previous year's catastrophic deficit, our current quarter is a different kettle of ________.",
     ["fish", "soup", "tea", "potatoes"],
     "'A different kettle of fish' is an idiom meaning a completely different situation or matter.",
     "Managing ten employees is fine, but overseeing a multinational division is a different kettle of fish."),
    ("Idiomatic Stances", 4, "The rebel MPs took a firm ________ against proposed cuts to rural bus subsidies.",
     ["stand", "step", "walk", "posture"],
     "'To take a stand (against something)' means to adopt a resolute, public position of resistance.",
     "Scientists took a firm stand against political attempts to alter climate change reports."),
    ("Verb + Noun Collocations", 5, "The scholar took great ________ to translate the ancient Syriac verses faithfully.",
     ["pains", "care", "labor", "toil"],
     "'To take great pains (to do something)' is a high-register idiom meaning to make exhaustive, diligent efforts.",
     "She took great pains to verify the genealogical provenance of every family heirloom."),
    ("Prepositional Collocations", 3, "His personal account of the expedition is at ________ with official naval records.",
     ["variance", "dispute", "contrast", "divergence"],
     "'At variance with' is the formal idiom meaning in disagreement, contradiction, or conflict with.",
     "Her optimistic assessment of retail sales is at variance with the central bank's forecast."),
    ("Idioms of Memory", 4, "The old schoolhouse brought memories flooding ________ from his childhood.",
     ["back", "in", "out", "over"],
     "'To bring memories flooding back' is the evocative standard collocation.",
     "Listening to the vinyl record brought memories of her student years flooding back."),
    ("Prepositional Phrases", 3, "The soldiers were placed on standby in ________ of civil unrest during the election.",
     ["case", "event", "view", "time"],
     "'In case of + noun' (or in the event of) signifies preparation for a possible occurrence.",
     "Emergency generators are maintained in case of sudden electrical grid failure."),
    ("Idiomatic Readiness", 4, "When the alarm sounded, the coastguard cutters were ready at a moment's ________.",
     ["notice", "warning", "attention", "time"],
     "'At a moment's notice' means immediately, without advance preparation or delay.",
     "The pediatric surgeon must be prepared to perform operations at a moment's notice."),
    ("Idioms of Restraint", 4, "He had to bite his ________ to avoid uttering a furious retort to the rude customs inspector.",
     ["tongue", "lip", "cheek", "jaw"],
     "'To bite one's tongue' means to make a determined, difficult effort to remain silent.",
     "I had to bite my tongue during the meeting to prevent an unseemly public argument."),
    ("Idioms of Simplicity", 2, "Assembling the flat-pack bookshelf proved as easy as ________.",
     ["pie", "cake", "bread", "soup"],
     "'As easy as pie' (or a piece of cake) is an everyday idiom meaning remarkably straightforward.",
     "Once you understand the basic formula, solving quadratic equations is as easy as pie."),
    ("Idioms of Completion", 3, "Let's call it a ________ and resume our debugging session tomorrow morning.",
     ["day", "night", "stop", "rest"],
     "'To call it a day' means to decide to stop working on an activity for the rest of the day.",
     "After twelve hours of tedious spreadsheet calculations, we decided to call it a day."),
    ("Verb + Preposition", 3, "She prides herself ________ her encyclopedic recall of botanical classifications.",
     ["on", "in", "for", "with"],
     "'To pride oneself on (something)' is the correct prepositional collocation.",
     "The hotel prides itself on offering exceptional personalized service to every guest."),
    ("Idioms of Reality", 4, "When her savings ran dry, she had to face the ________ and look for employment.",
     ["music", "truth", "facts", "reality"],
     "'To face the music' means to confront the unpleasant consequences of one's actions or situation.",
     "He knew he had failed the inspection and would have to face the music before the director."),
    ("Prepositional Phrases", 4, "The executive was dismissed on the ________ of chronic insubordination.",
     ["grounds", "reasons", "bases", "causes"],
     "'On the grounds of (something)' is the formal legal and administrative prepositional phrase.",
     "The appeal was rejected on the grounds of insufficient corroborating evidence."),
    ("Idiomatic Speed", 3, "News of the royal abdication spread like ________ through the capital streets.",
     ["wildfire", "lightning", "wind", "water"],
     "'To spread like wildfire' is the classic simile denoting extremely rapid dissemination.",
     "Rumors of an impending corporate merger spread like wildfire across the trading floor."),
    ("Verb + Noun Collocations", 4, "The municipal council decided to ________ homage to the fallen soldiers with a marble cenotaph.",
     ["pay", "give", "render", "make"],
     "'To pay homage to (someone)' is the formal established collocation.",
     "Literary scholars gathered in Stratford to pay homage to Shakespeare's enduring legacy."),
    ("Idioms of Agreement", 3, "After hours of haggling, the two merchants finally struck a ________.",
     ["deal", "bargain", "pact", "trade"],
     "'To strike a deal' (or strike a bargain) means to reach a mutually satisfactory agreement.",
     "The studio struck a deal with the streaming network to distribute the documentary worldwide."),
    ("Idioms of Hesitation", 4, "She had second ________ about accepting the overseas posting so close to her wedding.",
     ["thoughts", "minds", "feelings", "doubts"],
     "'To have second thoughts (about something)' means to doubt or reconsider a prior decision.",
     "He began having second thoughts about climbing the summit as storm clouds gathered."),
    ("Prepositional Phrases", 3, "The defendant was acquitted ________ account of procedural irregularities during his arrest.",
     ["on", "by", "for", "in"],
     "'On account of' means because of or by reason of.",
     "The cross-country train was delayed on account of heavy snowfall in the mountain passes."),
    ("Idiomatic Focus", 4, "Keep an ________ on the pressure gauge while the steam valve is open.",
     ["eye", "ear", "hand", "arm"],
     "'To keep an eye on (something)' means to watch, monitor, or supervise carefully.",
     "Please keep an eye on the soup simmering on the stove while I fetch firewood."),
    ("Idioms of Discovery", 4, "The investigative journalists caught the smuggling ring ________-handed.",
     ["red", "bare", "empty", "open"],
     "'To catch someone red-handed' means to apprehend someone in the very act of committing a crime.",
     "Security guards caught the trespasser red-handed as he attempted to pick the vault lock."),
    ("Prepositional Phrases", 4, "The young barrister was admitted to the Bar ________ course.",
     ["in due", "at due", "by due", "on due"],
     "'In due course' is a formal phrase meaning at a suitable, proper, or appropriate future time.",
     "Your application will be evaluated and formal notification issued in due course."),
    ("Idioms of Vulnerability", 5, "His inability to handle financial pressure proved to be his Achilles' ________.",
     ["heel", "tendon", "foot", "sole"],
     "'An Achilles' heel' is a fatal weakness or vulnerable spot in an otherwise strong entity.",
     "A lack of digital infrastructure was the legacy retail chain's Achilles' heel."),
    ("Idioms of Revelation", 4, "During the heated trial, the witness let the cat out of the ________.",
     ["bag", "box", "cage", "basket"],
     "'To let the cat out of the bag' means to reveal a secret prematurely or inadvertently.",
     "We wanted the retirement party to be a surprise, but Michael let the cat out of the bag."),
    ("Prepositional Idioms", 4, "Her groundbreaking monograph on thermodynamics stands head and ________ above competing textbooks.",
     ["shoulders", "arms", "neck", "knees"],
     "'To stand head and shoulders above (others)' means to be vastly superior to peers.",
     "As a concert pianist, she stood head and shoulders above other conservatory graduates."),
    ("Idioms of Distance", 3, "The reclusive billionaire preferred to keep the media at arm's ________.",
     ["length", "distance", "reach", "span"],
     "'To keep someone at arm's length' means to avoid intimacy, close contact, or familiarity.",
     "He kept his new acquaintances at arm's length until he could assess their trustworthiness."),
    ("Verb + Noun Collocations", 5, "The prime minister sought to ________ the fears of the public regarding food security.",
     ["allay", "relax", "appease", "slake"],
     "'To allay fears' (or concerns/doubts) is the formal collocation meaning to diminish or put to rest.",
     "The health minister held a press briefing to allay public concerns about the new variant."),
    ("Prepositional Phrases", 3, "The troops were instructed to remain in formation ________ all costs.",
     ["at", "with", "by", "on"],
     "'At all costs' means regardless of the effort, sacrifice, or difficulty involved.",
     "The vital mountain pass had to be defended at all costs against advancing forces."),
    ("Idiomatic Surprise", 4, "The news of the sudden factory closure came like a bolt from the ________.",
     ["blue", "sky", "cloud", "dark"],
     "'A bolt from the blue' describes a totally unexpected, sudden, and shocking occurrence.",
     "Her resignation letter was a bolt from the blue to colleagues who expected her promotion.")
]

print("Loaded NEW_COLLOC definitions.")
