# scripts/data_definitions_expansion2.py
# Additions for Phrasal Verbs and Confusables

NEW_PHRASAL = [
    ("bear out", 3, "Subsequent archaeological excavations ________ the truth of the ancient chronicles.",
     ["bore out", "carried out", "held out", "stood out"],
     "'To bear out' means to confirm, substantiate, or verify the truth of an assertion.",
     "Statistical data bore out her prediction that inflation would taper off by winter."),
    ("branch out", 3, "The boutique coffee roaster decided to ________ into gourmet bakery goods.",
     ["branch out", "reach forth", "shoot over", "fork off"],
     "'To branch out' means to expand one's activities or business into a new field.",
     "After years in commercial litigation, she decided to branch out into human rights law."),
    ("bring about", 2, "Rapid advances in microprocessing ________ revolutionary changes in medical diagnostics.",
     ["brought about", "took about", "came about", "put about"],
     "'To bring about' means to cause something to happen or bring to fruition.",
     "The new environmental treaty brought about a significant decline in sulfur emissions."),
    ("bring off", 4, "Against all expert predictions, the inexperienced diplomat managed to ________ a historic ceasefire.",
     ["bring off", "pull off", "take off", "carry off"],
     "'To bring off' means to achieve something difficult successfully.",
     "It was a difficult corporate acquisition, but senior management managed to bring it off."),
    ("brush up on", 3, "Before relocating to the Geneva headquarters, she spent a month ________ her conversational French.",
     ["brushing up on", "polishing up to", "scrubbing over", "rubbing down on"],
     "'To brush up on' means to refresh one's knowledge or skill in a subject.",
     "I need to brush up on international tax regulations before meeting our foreign clients."),
    ("contract out", 4, "The local health authority decided to ________ laboratory testing to a private diagnostics firm.",
     ["contract out", "farm in", "hire out", "lease off"],
     "'To contract out' means to arrange for work to be done by an outside contractor.",
     "The city council contracted out street maintenance to reduce municipal overhead."),
    ("crack down on", 3, "The maritime agency announced stricter patrols to ________ illegal trawling in protected waters.",
     ["crack down on", "slam down on", "break into", "press down to"],
     "'To crack down on' means to take severe, forceful measures against lawbreaking.",
     "Border authorities cracked down on counterfeit luxury goods entering the country."),
    ("dry up", 2, "When private donations began to ________, the arts foundation turned to public endowments.",
     ["dry up", "drain out", "wither down", "leak away"],
     "'To dry up' means to decrease and stop existing or being available.",
     "Global credit dried up rapidly during the initial months of the banking crisis."),
    ("embark on", 3, "Having completed his fellowship, the surgeon was eager to ________ an independent research career.",
     ["embark on", "enter on", "set on", "take on"],
     "'To embark on' means to start a new project, journey, or significant course of action.",
     "She embarked on an ambitious three-year study of migratory seabirds."),
    ("fence in", 4, "The young creative director felt increasingly ________ by rigid corporate branding guidelines.",
     ["fenced in", "walled out", "caged off", "hedged over"],
     "'To fence in' means to restrict someone's freedom or choices severely.",
     "Artists often feel fenced in when working within strictly commercial genres."),
    ("filter through", 4, "It took several days for news of the remote earthquake to ________ to international press bureaus.",
     ["filter through", "percolate over", "strain down", "sift in"],
     "'To filter through' means to become known or penetrate gradually and slowly.",
     "Whispers of an impending boardroom reorganization began to filter through the office."),
    ("fit in with", 3, "Her innovative design concepts did not readily ________ the conservative ethos of the firm.",
     ["fit in with", "suit up to", "match on with", "blend out of"],
     "'To fit in with' means to be harmonious, compatible, or consistent with something.",
     "Does the proposed scheduling fit in with your current departmental commitments?"),
    ("follow through", 3, "Although the governor promised sweeping judicial reforms, he failed to ________ with funding.",
     ["follow through", "carry on", "go through", "lead past"],
     "'To follow through' means to complete an activity or fulfill an intention thoroughly.",
     "You must follow through with your training if you wish to pass the mountaineering qualification."),
    ("forge ahead", 4, "Despite fierce union objections, the transport board voted to ________ with automation.",
     ["forge ahead", "plow over", "drive forward", "stride out"],
     "'To forge ahead' means to proceed determinedly and vigorously with an initiative.",
     "Engineers forged ahead with drilling operations despite inclement Arctic weather."),
    ("iron out", 3, "The two trade envoys scheduled an extra session to ________ the final tariff exemptions.",
     ["iron out", "smooth off", "press down", "flatten out"],
     "'To iron out' means to resolve or eliminate minor difficulties or disputes.",
     "We need to iron out a few lingering contractual ambiguities before signing."),
    ("leap at", 4, "When offered a guest professorship at Oxford, the young scholar ________ the opportunity.",
     ["leapt at", "jumped on", "sprang to", "bounded for"],
     "'To leap at (an opportunity)' means to accept a chance eagerly and without hesitation.",
     "He leapt at the chance to study marine biology on a dedicated research vessel."),
    ("measure up to", 4, "The sequel to the award-winning historical drama failed to ________ the high standards of the original.",
     ["measure up to", "size up to", "reach up on", "count into"],
     "'To measure up to' means to meet expectations, standards, or requirements.",
     "Her debut performance measured up to the highest standards of the Royal Ballet."),
    ("nose around", 3, "Investigative reporters spent the afternoon ________ the municipal archives in search of land deeds.",
     ["nosing around", "sniffing out", "smelling into", "poking off"],
     "'To nose around' means to pry, snoop, or search inquisitively for information.",
     "Security guards warned visitors not to nose around the private laboratory wings."),
    ("pass off as", 4, "The dealer was convicted of attempting to ________ clever replicas as genuine Ming porcelain.",
     ["pass off as", "fob off to", "palm down as", "ring out for"],
     "'To pass off as' means to falsely represent something fraudulent as authentic.",
     "He tried to pass off his amateur sketches as the work of an established modernist."),
    ("phase out", 3, "The manufacturing plant agreed to ________ coal-fired boilers over the next five years.",
     ["phase out", "wind down", "stage off", "dwindle out"],
     "'To phase out' means to discontinue or eliminate gradually in stages.",
     "Government subsidies for fossil fuel exploration will be phased out by 2030."),
    ("pull off", 4, "Against all bookmakers' predictions, the young chess master ________ an unexpected victory.",
     ["pulled off", "carried on", "struck out", "drew over"],
     "'To pull off' means to achieve something difficult or audacious unexpectedly.",
     "It was an astonishing diplomatic triumph that few believed she could pull off."),
    ("push for", 3, "Environmental advocacy organizations continue to ________ stricter limits on chemical runoff.",
     ["push for", "press into", "urge on", "thrust toward"],
     "'To push for' means to advocate strongly, demand, or campaign vigorously for something.",
     "Local community groups are pushing for the construction of a new public sports center."),
    ("reel off", 4, "Without consulting her index cards, the historian ________ the names and reign dates of every Tudor monarch.",
     ["reeled off", "rattled over", "dashed down", "spun off"],
     "'To reel off' means to recite a long list of facts or numbers effortlessly from memory.",
     "The sommelier effortlessly reeled off tasting notes for thirty distinct vintage wines."),
    ("rein in", 4, "The finance committee moved quickly to ________ excessive executive travel expenditures.",
     ["rein in", "curb off", "strap down", "bridle over"],
     "'To rein in' means to restrict, limit, or control excessive behavior or spending.",
     "Central bankers took steps to rein in soaring residential mortgage borrowing."),
    ("ride out", 4, "Thanks to conservative capital reserves, the regional cooperative managed to ________ the economic downturn.",
     ["ride out", "sail through", "weather off", "drift past"],
     "'To ride out' means to survive or withstand a storm or crisis successfully.",
     "The fishing trawler rode out the gale in the shelter of a natural fjord."),
    ("scrape through", 3, "Having revised for only two days, he barely managed to ________ the advanced organic chemistry exam.",
     ["scrape through", "breeze through", "brush past", "skim over"],
     "'To scrape through' means to succeed or pass by the narrowest of margins.",
     "The minority coalition scraped through the confidence vote by a single ballot."),
    ("settle up", 3, "Before checking out of the ski chalet, we met in the lobby to ________ our shared dining expenses.",
     ["settle up", "pay off", "clear down", "square off"],
     "'To settle up' means to pay what is owed on an account or share expenses evenly.",
     "Let us settle up for the taxi fare before we enter the restaurant."),
    ("shell out", 4, "Homeowners were forced to ________ thousands of pounds to replace compromised lead plumbing.",
     ["shell out", "fork down", "dish over", "cough off"],
     "'To shell out' means to spend or pay a substantial, often unwelcome sum of money.",
     "The university shelled out millions to renovate the Victorian chemistry laboratories."),
    ("shoot down", 3, "The editorial board was swift to ________ the intern's unverified conspiracy theories.",
     ["shoot down", "strike off", "blast over", "gun down"],
     "'To shoot down' means to reject, dismiss, or demolish an idea or proposal forcefully.",
     "Senior architects shot down the cost-cutting proposal as aesthetically disastrous."),
    ("shrug off", 3, "Despite sustaining a bruised collarbone, the rugby captain ________ the injury and played on.",
     ["shrugged off", "brushed down", "waved past", "shook away"],
     "'To shrug off' means to treat something painful or critical as unimportant or negligible.",
     "An experienced politician learns to shrug off partisan editorial attacks."),
    ("single out", 4, "The headmistress ________ Maria for her extraordinary courage during the river rescue.",
     ["singled out", "picked over", "pointed down", "marked off"],
     "'To single out' means to select, highlight, or praise one person from a group.",
     "Reviewers singled out the costume designer for special commendation."),
    ("size up", 3, "The boxing champion spent the initial two rounds carefully ________ his challenger's reach and footwork.",
     ["sizing up", "weighing down", "checking over", "gauging into"],
     "'To size up' means to assess or evaluate someone or something carefully.",
     "Recruiters spent the interview sizing up the candidate's strategic problem-solving abilities."),
    ("slack off", 2, "Senior students were warned not to ________ during the final weeks preceding GCSE examinations.",
     ["slack off", "drop out", "ease away", "drift over"],
     "'To slack off' means to decrease one's effort, diligence, or concentration.",
     "If you slack off in basic training, you will not qualify for the specialist airborne unit."),
    ("spark off", 4, "The controversial cartoons ________ nationwide demonstrations outside government ministries.",
     ["sparked off", "fired up", "struck over", "flamed out"],
     "'To spark off' means to ignite, trigger, or precipitate sudden unrest or debate.",
     "The introduction of fuel rationing sparked off mass transportation protests."),
    ("spell out", 3, "The contract must ________ the exact penalties for late delivery of structural steel.",
     ["spell out", "write off", "read down", "print forth"],
     "'To spell out' means to explain or define something in full, unambiguous, explicit detail.",
     "The safety manual spells out the precise emergency evacuation procedures."),
    ("square up to", 5, "It is time for the municipal authorities to ________ the chronic reality of youth unemployment.",
     ["square up to", "face down on", "level into", "head up to"],
     "'To square up to' means to face, confront, or tackle a difficult situation courageously.",
     "The medical establishment must square up to systemic disparities in public healthcare access."),
    ("stamp out", 3, "Public health officials worked round the clock to ________ the outbreak of cholera in the delta.",
     ["stamp out", "tread down", "crush off", "step over"],
     "'To stamp out' means to extinguish, eradicate, or suppress something completely.",
     "Strict disciplinary policies were implemented to stamp out bullying in secondary schools."),
    ("stand down", 4, "Following the parliamentary scandal, the minister agreed to ________ before the inquiry convened.",
     ["stand down", "step off", "drop over", "hold back"],
     "'To stand down' means to resign or withdraw formally from a post or election.",
     "The veteran board chairman decided to stand down after twenty-five years of leadership."),
    ("string along", 4, "She realized that the venture capitalist was merely ________ her while negotiating with a rival.",
     ["stringing along", "trailing off", "leading on", "winding up"],
     "'To string along' means to deceive or lead someone on dishonestly over time.",
     "Do not string prospective buyers along if you have already accepted an offer."),
    ("swallow up", 4, "Runaway legal fees threatened to ________ the modest estate left to the orphans.",
     ["swallow up", "gulp down", "ingest over", "soak off"],
     "'To swallow up' means to absorb, engulf, or consume something completely.",
     "The vast multinational corporation swallowed up several dozen regional family enterprises."),
    ("talk down to", 3, "Patients appreciated the physician because he never ________ them, explaining diagnoses clearly.",
     ["talked down to", "spoke down on", "looked down on", "chatted to"],
     "'To talk down to' means to speak to someone in a patronizing, condescending way.",
     "A good instructor never talks down to students, but inspires independent critical inquiry."),
    ("tap into", 4, "The innovative marketing campaign managed to ________ widespread public nostalgia for the 1980s.",
     ["tap into", "pipe into", "mine on", "drain from"],
     "'To tap into' means to exploit, access, or utilize a resource, sentiment, or energy.",
     "Renewable energy companies are learning to tap into geothermal springs in volcanic basins."),
    ("tear into", 4, "The defense attorney proceeded to ________ the credibility of the prosecution's witness during cross-examination.",
     ["tear into", "rip off", "slash down", "cut into"],
     "'To tear into' means to criticize or attack someone or something ferociously.",
     "Literary critics tore into the bestselling thriller, mocking its wooden characterization."),
    ("thrive on", 3, "Investigative journalists often ________ the adrenaline and pressure of breaking breaking investigative scandals.",
     ["thrive on", "grow on", "prosper in", "feed upon"],
     "'To thrive on' means to flourish, prosper, or enjoy something challenging or stressful.",
     "She thrives on high-stakes courtroom litigation and twelve-hour trial sessions."),
    ("thumb through", 3, "While waiting for her dental appointment, she ________ several glossy lifestyle magazines.",
     ["thumbed through", "fingered over", "leafed into", "glanced down"],
     "'To thumb through' means to turn the pages of a book, document, or magazine quickly.",
     "He thumbed through the antique atlas, admiring the hand-tinted cartography."),
    ("touch upon", 4, "The introductory chapter only managed to ________ the complex macroeconomic causes of the recession.",
     ["touch upon", "brush on", "glance over", "tap at"],
     "'To touch upon' means to mention or treat a subject briefly in passing.",
     "The symposium touched upon ethical quandaries surrounding artificial generative intelligence."),
    ("track down", 3, "After searching through diocesan archives for six months, the genealogist ________ the baptismal certificate.",
     ["tracked down", "hunted over", "trailed out", "spotted up"],
     "'To track down' means to find or locate someone or something after a diligent search.",
     "Detectives tracked down the stolen delivery truck in an abandoned industrial park."),
    ("yield to", 4, "Under overwhelming pressure from international credit agencies, the government was forced to ________ demands for fiscal austerity.",
     ["yield to", "bend to", "bow on", "give up to"],
     "'To yield to' means to surrender, submit, or give way to pressure or temptation.",
     "He refused to yield to despair, continuing his medical research in a modest garage laboratory."),
    ("wrap up", 2, "Let us ________ the conference call so that our Tokyo colleagues can retire for the evening.",
     ["wrap up", "fold up", "pack down", "close out"],
     "'To wrap up' means to conclude, finish, or bring an event or meeting to an end.",
     "We hope to wrap up negotiations by Friday afternoon before the markets close."),
    ("wipe out", 3, "The devastating tsunami ________ several coastal fishing hamlets within fifteen terrifying minutes.",
     ["wiped out", "swept over", "brushed off", "cleared down"],
     "'To wipe out' means to destroy, eliminate, or erase completely.",
     "Catastrophic flash floods wiped out three agricultural irrigation canals in the valley.")
]

NEW_CONFUSABLES = [
    ("Elicit vs Illicit", 3, "The defense attorney’s tactful questioning was designed to ________ truthful testimony from the nervous witness.",
     ["elicit", "illicit", "elide", "solicit"],
     "'Elicit' is a verb meaning to draw forth or evoke. 'Illicit' is an adjective meaning illegal or prohibited.",
     "The detective was able to elicit crucial details regarding the getaway vehicle."),
    ("Eminent vs Imminent vs Immanent", 4, "A panel of ________ neurologists was assembled to evaluate the experimental concussion therapy.",
     ["eminent", "imminent", "immanent", "emanating"],
     "'Eminent' means distinguished, high-ranking, or famous. 'Imminent' means impending; 'immanent' means inherent.",
     "The lecture was delivered by an eminent scholar of Byzantine numismatics."),
    ("Exalt vs Exult", 4, "Ancient Roman odes were composed to ________ the martial virtues of the emperor.",
     ["exalt", "exult", "excoriate", "extol"],
     "'To exalt' means to praise, glorify, or raise high. 'To exult' means to rejoice or feel triumphant.",
     "Hymns were sung to exalt the patron saint on the eve of the festival."),
    ("Ordinance vs Ordnance", 5, "The municipal council passed a strict ________ prohibiting open fires in residential gardens during August.",
     ["ordinance", "ordnance", "ordonnance", "ordaining"],
     "'Ordinance' is an authoritative municipal law or decree. 'Ordnance' refers to military weaponry and ammunition.",
     "A local ordinance forbids parking commercial vans on residential streets overnight."),
    ("Pique vs Peak vs Peek", 4, "The eccentric mystery novel was crafted to ________ the reader's curiosity from the opening sentence.",
     ["pique", "peak", "peek", "peep"],
     "'To pique' means to stimulate, arouse, or provoke interest or resentment.",
     "The unexpected discovery piqued the archaeologist's professional curiosity."),
    ("Waive vs Wave", 3, "The university decided to ________ the application fee for low-income postgraduate applicants.",
     ["waive", "wave", "waver", "waffle"],
     "'To waive' means to refrain from demanding compliance with a rule, fee, or right.",
     "The airline agreed to waive change penalties due to severe weather cancellations."),
    ("Stationary vs Stationery", 3, "The vehicle remained ________ at the traffic lights for three minutes while the motor stalled.",
     ["stationary", "stationery", "stationing", "stationer"],
     "'Stationary' (with 'a') means not moving; motionless. 'Stationery' (with 'e') means writing materials.",
     "Bicycle commuters were forced to weave around stationary delivery lorries in the cycle lane."),
    ("Incite vs Insight", 4, "The author offers profound psychological ________ into the motives of the tragic protagonist.",
     ["insight", "incite", "inspire", "indict"],
     "'Insight' is deep understanding or intuition. 'Incite' is a verb meaning to stir up or provoke unrest.",
     "Her monograph provides remarkable insight into early medieval monastic administration."),
    ("Grisly vs Grizzly", 3, "Detectives were disturbed by the ________ details revealed during the forensic examination.",
     ["grisly", "grizzly", "gristly", "grimy"],
     "'Grisly' means gruesome, horrific, or causing revulsion. 'Grizzly' refers to a North American brown bear.",
     "The historical chronicle recounts the grisly execution of the rebel conspirators."),
    ("Hoard vs Horde", 4, "Archaeologists discovered an invaluable ________ of silver Anglo-Saxon coins buried in a clay amphora.",
     ["hoard", "horde", "whore", "herd"],
     "A 'hoard' is an accumulated secret cache or treasure. A 'horde' is a large, unruly crowd of people.",
     "The miser accumulated a vast hoard of banknotes inside his mattress."),
    ("Premise vs Premises", 4, "The philosophical deduction rests upon the unproven ________ that human nature is fundamentally rational.",
     ["premise", "premises", "premonition", "premising"],
     "A 'premise' (singular) is a foundational assumption or proposition. 'Premises' (plural) refers to buildings/grounds.",
     "If your initial premise is flawed, your entire subsequent deduction is invalid."),
    ("Wreak vs Wreck", 4, "The coastal gale threatened to ________ immense destruction upon fragile oyster farming beds.",
     ["wreak", "wreck", "reek", "wring"],
     "'To wreak (havoc/destruction/vengeance)' means to inflict or cause. 'To wreck' is to ruin a physical structure.",
     "Invasive beetles can wreak catastrophic damage upon commercial citrus orchards."),
    ("Censor vs Censer vs Sensor", 4, "During religious services, the altar boy carried a smoking bronze ________ filled with burning frankincense.",
     ["censer", "censor", "sensor", "scenter"],
     "A 'censer' is a vessel in which incense is burned during religious ceremonies.",
     "Fragrant clouds of myrrh rose as the priest swung the silver censer."),
    ("Assent vs Ascent", 3, "The mountaineering team commenced their final ________ of Mount Everest at midnight.",
     ["ascent", "assent", "accent", "ascending"],
     "'Ascent' is a climb or upward path. 'Assent' is formal agreement or approval.",
     "A grueling six-hour ascent brought the climbers to the summit ridge."),
    ("Complementary vs Complimentary", 3, "The architect and interior designer possessed ________ skills that enhanced the finished villa.",
     ["complementary", "complimentary", "complimenting", "complex"],
     "'Complementary' means combining in such a way as to enhance or complete each other's qualities.",
     "The two musicians played in complementary styles that created rich harmonic textures."),
    ("Council vs Counsel", 3, "The local municipal ________ voted unanimously to construct a new community park.",
     ["council", "counsel", "councillor", "counselor"],
     "A 'council' is an administrative, legislative, or advisory body of people.",
     "The town council meets every second Tuesday to review planning applications."),
    ("Flare vs Flair", 3, "The stranded mariners launched a red emergency ________ to alert the search aircraft.",
     ["flare", "flair", "flareup", "flairing"],
     "A 'flare' is a bright flame or light used as a signal. 'Flair' is instinctive talent or stylish aptitude.",
     "A bright distress flare illuminated the night sky above the stormy coastline."),
    ("Foreword vs Forward", 3, "The renowned Cambridge historian contributed an eloquent ________ to the revised edition.",
     ["foreword", "forward", "forefront", "forthward"],
     "A 'foreword' is a short introductory preface to a book, usually by someone other than the author.",
     "In her foreword to the anthology, the poet praised the young translators' accuracy."),
    ("Marshal vs Martial", 4, "The emperor declared ________ law following widespread street protests across the province.",
     ["martial", "marshal", "marcial", "marshaling"],
     "'Martial' relates to warfare, soldiers, or the military. 'To marshal' is to arrange or gather.",
     "Martial law was imposed, placing soldiers on street corners and establishing a dusk curfew."),
    ("Precedent vs President", 3, "The appellate court's landmark verdict created a binding legal ________ for all subsequent disputes.",
     ["precedent", "president", "precedence", "presidency"],
     "A 'precedent' is an earlier event or legal decision serving as an authoritative guide in future cases.",
     "This ruling establishes a dangerous precedent for civil liberties during wartime."),
    ("Allude vs Elude", 4, "Despite exhaustive searches by three police forces, the fugitive managed to ________ capture for eighteen months.",
     ["elude", "allude", "illude", "delude"],
     "'To elude' means to escape or evade capture, comprehension, or memory.",
     "The precise biological mechanism underlying sleep continues to elude neuroscientists."),
    ("Affect vs Effect (Nominal)", 4, "The environmental impact report detailed the adverse ________ of pesticide runoff on freshwater fish.",
     ["effects", "affects", "afflictions", "effacements"],
     "As a noun, 'effect' denotes a result or consequence. ('Affect' as a noun is rare and refers to psychological emotion).",
     "The economic effects of the embargo were felt immediately by manufacturing firms."),
    ("Deprecate vs Depreciate", 4, "Automobiles typically ________ in market value by twenty percent within their first year of registration.",
     ["depreciate", "deprecate", "deracinate", "deteriorate"],
     "'To depreciate' means to diminish in financial or monetary value over time.",
     "Currency depreciation made imported consumer electronics significantly more expensive."),
    ("Ingenious vs Ingenuous", 4, "The young engineer designed an ________ mechanism that doubled the thermal efficiency of the engine.",
     ["ingenious", "ingenuous", "indigenous", "ingratiating"],
     "'Ingenious' means clever, original, and brilliantly inventive.",
     "She devised an ingenious solution for storing rainwater during monsoon season."),
    ("Tortuous vs Torturous", 4, "The cross-country interrogation was a ________ psychological ordeal that lasted three sleepless days.",
     ["torturous", "tortuous", "torpid", "turgid"],
     "'Torturous' means causing severe pain, agony, or torture. 'Tortuous' means twisting or convoluted.",
     "Spending forty-eight hours in an unventilated railcar was a torturous experience."),
    ("Venal vs Venial", 4, "The investigative journalists exposed a ________ procurement ring within the ministry of transport.",
     ["venal", "venial", "vernal", "vicious"],
     "'Venal' means open to bribery or corruptible. 'Venial' means a minor, forgivable fault.",
     "A venal judge was convicted of taking bribes from organized crime cartels."),
    ("Loath vs Loathe", 3, "Vegetarians are often ________ to attend barbecues where heavy red meat is prepared.",
     ["loath", "loathe", "loathed", "loathing"],
     "'Loath' (adjective) means reluctant or unwilling. 'Loathe' (verb) means to detest.",
     "He was loath to criticize his mentor publicly despite significant theoretical differences."),
    ("Discreet vs Discrete", 4, "Diplomatic negotiations require ________ staff who never leak private discussions to journalists.",
     ["discreet", "discrete", "discretional", "discretive"],
     "'Discreet' means careful, prudent, and keeping things confidential. 'Discrete' means separate.",
     "The prime minister made discreet inquiries regarding the ambassador's loyalty."),
    ("Censure vs Censor", 4, "The military command moved to ________ all outgoing dispatches from frontline journalists.",
     ["censor", "censure", "sensor", "censer"],
     "'To censor' means to examine and suppress objectionable or sensitive material. 'To censure' is to criticize formally.",
     "Wartime authorities censored letters sent home by frontline infantrymen."),
    ("Historic vs Historical", 3, "The museum houses extensive ________ documents detailing 17th-century merchant shipping routes.",
     ["historical", "historic", "historied", "historicist"],
     "'Historical' means concerning or belonging to past history. 'Historic' means momentous or famous in history.",
     "Historical records indicate that the village was founded by Saxon settlers in 680 AD."),
    ("Elusive vs Illusive", 4, "The rare snow leopard proved remarkably ________, avoiding camera traps for three months.",
     ["elusive", "illusive", "delusive", "allusive"],
     "'Elusive' means difficult to find, track, achieve, or catch.",
     "A lasting political settlement remains elusive despite round-the-clock summits."),
    ("Persecute vs Prosecute", 4, "State prosecutors intend to ________ all corporate executives implicated in price-fixing schemes.",
     ["prosecute", "persecute", "peruse", "proscribe"],
     "'To prosecute' means to initiate legal proceedings against someone in a court of law.",
     "The crown will vigorously prosecute anyone tampering with jury members."),
    ("Principal vs Principle", 3, "The school ________ addressed the assembled students during the morning assembly.",
     ["principal", "principle", "principality", "principium"],
     "'Principal' refers to the head of a school, an important person, or capital sum. 'Principle' is a fundamental rule.",
     "The principal praised the debating team for winning the national trophy."),
    ("Alternate vs Alternative", 4, "If the mountain pass is blocked by snowdrifts, we will be forced to take an ________ route along the coast.",
     ["alternative", "alternate", "alternating", "alternation"],
     "'Alternative' means an available secondary option or substitute. 'Alternate' means every other.",
     "Scientists are researching alternative renewable energy sources to replace fossil fuels."),
    ("Allusion vs Illusion", 4, "Mirages in the desert create the optical ________ of shimmering pools of water.",
     ["illusion", "allusion", "delusion", "elusion"],
     "'An illusion' is a deceptive optical appearance or false impression.",
     "The magician created the illusion that the grand piano was levitating above the stage.")
]

print("Loaded NEW_PHRASAL and NEW_CONFUSABLES definitions.")
