# scripts/more_data.py
# Additional C2 items to exceed 1,000 unique questions in question bank

MORE_CLOZE_ITEMS = [
    ("transformation", "KWT: Idiom 'Dark'", 4,
     "The board of directors kept the shareholders completely uninformed about the impending merger.", "DARK",
     "The shareholders were completely ", " about the impending merger.",
     ["kept in the dark", "left in the dark"],
     "Use 'keep/leave someone in the dark'.",
     "'In the dark' means state of ignorance or not being informed about something.",
     "Workers were kept in the dark regarding the impending factory closure."),

    ("transformation", "KWT: Idiom 'Toll'", 4,
     "Prolonged stress gradually damaged her immune system.", "TOLL",
     "Prolonged stress gradually took a ", " her immune system.",
     ["heavy toll on", "toll on"],
     "Use 'take a toll on' or 'take a heavy toll on'.",
     "'To take a toll on' means to cause gradual damage or suffering.",
     "Years of coal mining had taken a devastating toll on his respiratory health."),

    ("transformation", "KWT: Idiom 'Chord'", 4,
     "Her impassioned speech deeply resonated with the working-class audience.", "CHORD",
     "Her impassioned speech struck a ", " the working-class audience.",
     ["chord with", "deep chord with"],
     "Use 'strike a chord with'.",
     "'To strike a chord with' means to cause someone to feel sympathy, emotion, or enthusiastic agreement.",
     "His humble origins struck a sympathetic chord with voters."),

    ("transformation", "KWT: Phrasal 'Down'", 4,
     "The company attributed its record profits to the devaluation of the currency.", "DOWN",
     "The company put its record ", " the devaluation of the currency.",
     ["profits down to", "success down to"],
     "Use 'put down to'.",
     "'To put down to' means to attribute something to a particular cause.",
     "She put her stammer down to sudden nervousness."),

    ("transformation", "KWT: Idiom 'Balance'", 5,
     "The fate of the endangered species remains highly precarious.", "BALANCE",
     "The fate of the endangered species hangs ", ".",
     ["in the balance", "firmly in the balance"],
     "Use 'hang in the balance'.",
     "'To hang in the balance' means to be in an undecided, critical, or precarious state.",
     "With voter turnout split evenly, the election hung in the balance."),

    ("transformation", "KWT: Idiom 'Music'", 4,
     "The corrupt executive finally had to accept the unpleasant consequences of his fraud.", "MUSIC",
     "The corrupt executive finally had to face ", ".",
     ["the music", "all the music"],
     "Use 'face the music'.",
     "'To face the music' means to accept the unpleasant consequences or criticism for one's actions.",
     "After skipping three mandatory audits, the treasurer had to face the music."),

    ("transformation", "KWT: Idiom 'Iceberg'", 4,
     "These documented financial irregularities are merely a small part of a much larger crisis.", "ICEBERG",
     "These documented financial irregularities are just the ", ".",
     ["tip of the iceberg", "very tip of the iceberg"],
     "Use 'the tip of the iceberg'.",
     "'The tip of the iceberg' denotes a small discernible part of a much greater concealed problem.",
     "The street protests were merely the tip of the iceberg of public indignation."),

    ("transformation", "KWT: Idiom 'Leaps'", 4,
     "Her conversational French improved remarkably fast during her summer in Lyon.", "LEAPS",
     "Her conversational French improved by ", " during her summer in Lyon.",
     ["leaps and bounds", "great leaps and bounds"],
     "Use 'by leaps and bounds'.",
     "'By leaps and bounds' means with rapid and spectacular progress.",
     "Scientific understanding of genomic medicine is advancing by leaps and bounds."),

    ("transformation", "KWT: Idiom 'Disguise'", 4,
     "Losing that dead-end job turned out to be an unexpected advantage in the long run.", "BLESSING",
     "Losing that dead-end job turned out to be a ", ".",
     ["blessing in disguise", "real blessing in disguise"],
     "Use 'a blessing in disguise'.",
     "'A blessing in disguise' is an apparent misfortune that eventually results in something good.",
     "Missing the train proved to be a blessing in disguise as the derailment occurred shortly after."),

    ("transformation", "KWT: Inversion 'Circumstances'", 5,
     "Staff members may not smoke anywhere inside the hospital under any circumstances.", "CIRCUMSTANCES",
     "Under ", " smoke anywhere inside the hospital.",
     ["no circumstances may staff members", "no circumstances should staff"],
     "Use 'Under no circumstances + modal + subject'.",
     "Fronted restrictive adverbial phrase requires subject-auxiliary inversion.",
     "Under no circumstances should pressurized containers be incinerated."),

    ("transformation", "KWT: Idiom 'Eye'", 4,
     "The two founders simply could not agree on the marketing strategy.", "EYE",
     "The two founders could not see ", " regarding the marketing strategy.",
     ["eye to eye", "eye to eye with each other"],
     "Use 'see eye to eye'.",
     "'To see eye to eye' means to be in full agreement with someone.",
     "The architect and the client rarely saw eye to eye on aesthetic choices."),

    ("transformation", "KWT: Idiom 'Desired'", 4,
     "The acoustics in the newly refurbished amphitheater were extremely disappointing.", "DESIRED",
     "The acoustics in the newly refurbished amphitheater left ", ".",
     ["much to be desired", "a lot to be desired"],
     "Use 'leave much to be desired'.",
     "'To leave much to be desired' means to be very unsatisfactory or inadequate.",
     "His punctuality and attention to protocol leave much to be desired."),

    ("transformation", "KWT: Idiom 'Counter'", 5,
     "The proposed deregulation directly conflicts with international environmental covenants.", "COUNTER",
     "The proposed deregulation runs ", " international environmental covenants.",
     ["counter to", "directly counter to"],
     "Use 'run counter to'.",
     "'To run counter to' means to be opposed to or conflict directly with a principle or rule.",
     "Such an autocratic decision runs counter to the democratic spirit of the union."),

    ("transformation", "KWT: Idiom 'Second'", 4,
     "He resented always having to play a subordinate role to his more charismatic brother.", "FIDDLE",
     "He resented having to play ", " his more charismatic brother.",
     ["second fiddle to", "the second fiddle to"],
     "Use 'play second fiddle to'.",
     "'To play second fiddle to' means to take a subordinate or secondary role to another person.",
     "She was tired of playing second fiddle to less competent colleagues."),

    ("transformation", "KWT: Idiom 'Towel'", 4,
     "After enduring eighteen grueling rounds of negotiations, the diplomat finally surrendered.", "TOWEL",
     "After eighteen grueling rounds of negotiations, the diplomat finally threw ", ".",
     ["in the towel", "in that towel"],
     "Use 'throw in the towel'.",
     "'To throw in the towel' means to give up, surrender, or admit defeat.",
     "Faced with mounting operational debts, the bistro owner threw in the towel."),

    ("transformation", "KWT: Idiom 'Corners'", 3,
     "The contractor tried to save money by doing things cheaply, which caused the ceiling to collapse.", "CORNERS",
     "The contractor cut ", " which caused the ceiling to collapse.",
     ["corners to save money", "corners on construction"],
     "Use 'cut corners'.",
     "'To cut corners' means to do something in the easiest, cheapest, or fastest way, disregarding quality.",
     "A reputable aviation firm never cuts corners when servicing turbine engines."),

    ("transformation", "KWT: Idiom 'Tree'", 4,
     "The detective was accusing the wrong suspect based on fabricated evidence.", "BARKING",
     "The detective was barking ", " based on fabricated evidence.",
     ["up the wrong tree", "at the wrong tree"],
     "Use 'bark up the wrong tree'.",
     "'To bark up the wrong tree' means to follow a mistaken line of thought or inquiry.",
     "If you think I authorized that payment, you are barking up the wrong tree."),

    ("transformation", "KWT: Idiom 'Weather'", 4,
     "The shipping company managed to survive the catastrophic economic recession.", "WEATHER",
     "The shipping company managed to ", " of the economic recession.",
     ["weather the storm", "weather the fierce storm"],
     "Use 'weather the storm'.",
     "'To weather the storm' means to successfully endure or survive a very difficult period.",
     "The family-run bookstore weathered the storm of digital competition."),

    ("transformation", "KWT: Idiom 'Touch'", 4,
     "The veteran diplomat seemed to have lost his ability to persuade foreign delegates.", "TOUCH",
     "The veteran diplomat seemed to have lost ", " foreign delegates.",
     ["his touch with", "his persuasive touch with"],
     "Use 'lose one's touch'.",
     "'To lose one's touch' means to no longer possess the skill or knack one once had.",
     "The master chef had not lost his touch, serving a sublime venison terrine."),

    ("transformation", "KWT: Idiom 'Handle'", 4,
     "When confronted with the accounting discrepancies, the store manager became suddenly enraged.", "HANDLE",
     "When confronted with the accounting discrepancies, the store manager flew ", ".",
     ["off the handle", "completely off the handle"],
     "Use 'fly off the handle'.",
     "'To fly off the handle' means to lose one's temper suddenly and violently.",
     "He is known to fly off the handle over the most trivial clerical errors.")
]

# Contextual Cloze additions (25 items)
MORE_CLOZE_CHOICE = [
    ("choice", "Cloze: Legal Register", 5,
     "The magistrate decreed that the controversial clauses were ________ and void under maritime law.",
     ["null", "blank", "voided", "hollow"],
     "'Null and void' is a fixed legal binomial collocation meaning having no legal force.",
     "The contract was declared null and void due to fraudulent misrepresentation."),

    ("choice", "Cloze: Academic Lexis", 4,
     "The research team sought to ________ the findings of the 1998 clinical trial.",
     ["replicate", "mimic", "parody", "feign"],
     "'To replicate' in scientific research means to duplicate or reproduce an experiment exactly.",
     "Independent laboratories were unable to replicate the cold fusion results."),

    ("choice", "Cloze: Sensory Nuance", 4,
     "The cellar had a damp, ________ smell reminiscent of rotting oak timbers.",
     ["musty", "rancid", "acrid", "sour"],
     "'Musty' describes a stale, mouldy, or damp smell characteristic of unventilated spaces.",
     "Old archives often smell musty after decades in basement vaults."),

    ("choice", "Cloze: Formal Adverbs", 4,
     "The parliamentarian ________ denied any knowledge of the clandestine offshore accounts.",
     ["categorically", "loosely", "feebly", "vaguely"],
     "'Categorically denied' is an emphatic high-level collocation meaning completely and without doubt.",
     "The spokesperson categorically denied all allegations of executive misconduct."),

    ("choice", "Cloze: Precision Verbs", 4,
     "Archaeologists meticulously ________ the earth around the buried Roman mosaic.",
     ["sifted", "scoured", "rummaged", "shuffled"],
     "'To sift' means to examine or filter through fine material with painstaking thoroughness.",
     "Detectives sifted through bags of shredded financial ledgers for clues."),

    ("choice", "Cloze: High Register Adjectives", 5,
     "The ambassador delivered a ________ rebuke that left no doubt about his government's outrage.",
     ["scathing", "tepid", "balmy", "diffuse"],
     "'Scathing' means severely critical, blistering, and cutting in tone.",
     "The theater reviewer published a scathing critique of the amateurish revival."),

    ("choice", "Cloze: Nuanced Modifiers", 4,
     "She made a ________ attempt to conceal her intense irritation behind a tight smile.",
     ["valiant", "limp", "slack", "crude"],
     "'A valiant attempt' describes a courageous, determined, though perhaps unsuccessful effort.",
     "Despite valiant efforts by paramedics, the patient could not be resuscitated."),

    ("choice", "Cloze: Rhetorical Precision", 5,
     "His argument rested upon an entirely ________ premise that fell apart under cross-examination.",
     ["flawed", "pristine", "sound", "taut"],
     "'A flawed premise' indicates a foundational defect in logic or fact that invalidates conclusions.",
     "The prosecution built its case on the flawed premise that only one suspect had access to the safe."),

    ("choice", "Cloze: Abstract Nuance", 4,
     "There was a ________ palpable tension in the boardroom as the proxy votes were tallied.",
     ["scarcely", "readily", "nearly", "fairly"],
     "'Palpable tension' collocated with 'readily' denotes tension so clear it can almost be touched.",
     "A palpable sense of anticipation settled over the Olympic stadium before the sprint final."),

    ("choice", "Cloze: Precision Phrasing", 4,
     "The newly appointed chief executive brought a ________ of fresh air to the stagnant company.",
     ["breath", "gust", "breeze", "draft"],
     "'A breath of fresh air' is an idiomatic phrase for someone or something refreshingly new and stimulating.",
     "Her dynamic leadership style was a breath of fresh air in the conservative law firm.")
]

MORE_GRAMMAR_ITEMS = [
    ("Inversion: Should anyone", 4,
     "________ anyone inquire about the confidential memorandum, please refer them to legal counsel.",
     ["Should", "Were", "Had", "Would"],
     "Inverted conditional with 'Should' replacing 'If anyone should inquire'.",
     "Should you encounter any difficulty operating the spectrometer, consult section four."),

    ("Inversion: Were she to", 5,
     "________ to accept the fellowship in Zurich, she would have to resign her university post.",
     ["Were she", "If she were", "Had she", "Should she be"],
     "Inverted second conditional: 'Were + subject + to infinitive'.",
     "Were the board to approve the proposal, capital expenditures would double next year."),

    ("Fronting: Hard as they tried", 4,
     "________ as they tried, the mountaineers could not locate the descent marker in the blizzard.",
     ["Hard", "Hardly", "As hard", "Though hard"],
     "Adverb + as/though + subject + verb creates an emphatic concessive subordinate clause.",
     "Fast as he ran, the messenger could not reach the garrison before nightfall."),

    ("Inversion: In no way", 4,
     "In no way ________ that the historical manuscripts were deliberately forged.",
     ["does this imply", "this implies", "implies this", "did this imply that"],
     "Fronted negative phrase 'In no way' triggers subject-auxiliary inversion.",
     "In no way do these preliminary figures represent our final audited turnover."),

    ("Subjunctive: Lest", 5,
     "The documents were sealed in an airtight vault lest humidity ________ the fragile parchment.",
     ["destroy", "destroys", "destroyed", "would destroy"],
     "'Lest' governs the base subjunctive or 'should + bare infinitive'.",
     "The sentry whispered his password lest the enemy overhear his voice."),

    ("Cleft Sentence: All that", 4,
     "________ matters now is securing medical evacuations for the stranded villagers.",
     ["All that", "It is", "What of", "That which"],
     "Pseudo-cleft focus construction: 'All that matters is...'.",
     "All that he desired was a quiet cottage where he could compose symphonies undisturbed."),

    ("Participle Clause: Seen from", 4,
     "________ from the summit, the glacial valley appeared as a silver ribbon winding through mist.",
     ["Seen", "Seeing", "Having seen", "To see"],
     "Past participle passive adverbial clause expressing perspective.",
     "Viewed from orbit, national boundaries dissolve into topographical topography."),

    ("Inversion: Not for one moment", 4,
     "Not for one moment ________ that the expedition would end in such catastrophe.",
     ["did we suspect", "we suspected", "had we suspected", "suspected we"],
     "Fronted negative time expression 'Not for one moment' requires auxiliary inversion.",
     "Not for one moment did she doubt the integrity of her business partner."),

    ("Subjunctive: Demand that", 4,
     "The international treaty demands that every signatory ________ hazardous chemical stockpiles.",
     ["dismantle", "dismantles", "dismantled", "would dismantle"],
     "Mandative verbs ('demand that') take the bare subjunctive.",
     "We demand that the prisoner be granted immediate access to an attorney."),

    ("Inversion: Adverb of Direction", 4,
     "Down ________ the torrential rain, flooding the city center within minutes.",
     ["poured", "it poured", "pouring", "did pour"],
     "Directional preposition fronting triggers full inversion with intransitive verbs of motion/occurrence.",
     "Into the banqueting hall swept the queen and her royal retinue."),

    ("Complex Modal: Cannot have", 4,
     "The artifact was locked in the safe; the thief ________ taken it without knowing the combination.",
     ["cannot have", "must not have", "should not have", "may not have"],
     "'Cannot have + past participle' expresses impossibility in the past.",
     "She cannot have known about the party because we kept it completely confidential."),

    ("Conditionals: But for", 4,
     "________ for the swift reaction of the lifeguard, the toddler would have drowned.",
     ["But", "Only", "Except", "Save"],
     "'But for + noun' means 'If it had not been for'.",
     "But for his stubborn optimism, the expedition would have turned back at the second camp."),

    ("Fronted Adjective: Rich as", 4,
     "________ as he was, the recluse lived in austere simplicity without luxury.",
     ["Rich", "Richer", "Being rich", "Though rich"],
     "Adjective fronting with 'as' conveys concession ('Although he was rich').",
     "Proud as she was, she was forced to seek financial charity from estranged relatives."),

    ("Formulaic Subjunctive: God forbid", 4,
     "God ________ that our country should ever plunge into another sectarian conflict.",
     ["forbid", "forbids", "forbade", "has forbidden"],
     "'God forbid' is a formulaic optative subjunctive expressing fervent hope that something will not happen.",
     "God forbid that we should neglect our moral duty to future generations."),

    ("Inversion: Only by chance", 4,
     "Only by chance ________ the missing archival diary in the monastery attic.",
     ["did the researcher discover", "the researcher discovered", "discovered the researcher", "was the researcher discovered"],
     "Fronted 'Only by [phrase]' triggers auxiliary inversion in the main clause.",
     "Only through rigorous practice will an acrobat master such perilous trapeze stunts."),

    ("Inversion: Scarcely ever", 4,
     "Scarcely ever ________ such astonishing display of virtuosity on the harpsichord.",
     ["has an audience heard", "an audience has heard", "heard an audience", "an audience heard"],
     "Fronted restrictive adverb 'Scarcely ever' requires subject-auxiliary inversion.",
     "Scarcely ever had the cathedral choir sounded so sublime."),

    ("Inversion: Not once", 4,
     "Not once ________ during the three-hour cross-examination by the prosecutor.",
     ["did the defendant waver", "the defendant wavered", "wavered the defendant", "had the defendant wavered"],
     "Fronted negative 'Not once' mandates subject-auxiliary inversion.",
     "Not once did he apologize for his reckless driving."),

    ("Inversion: Only later", 4,
     "Only later ________ that the priceless oil painting had been replaced with a replica.",
     ["did curators discover", "curators discovered", "discovered curators", "had curators discovered"],
     "Fronted 'Only later' triggers auxiliary inversion in the main clause.",
     "Only later did the detective realize the significance of the torn railway ticket."),

    ("Inversion: Under no obligation", 4,
     "Under no obligation ________ to answer questions without your legal representative present.",
     ["are you", "you are", "do you be", "can you be to"],
     "Fronted restrictive phrase 'Under no obligation' triggers subject-auxiliary inversion.",
     "Under no obligation is any citizen compelled to incriminate themselves."),

    ("Inversion: On no condition", 4,
     "On no condition ________ allow unauthorized personnel into the server room.",
     ["may you", "you may", "can you the", "you can"],
     "Fronted negative condition requires modal-subject inversion.",
     "On no condition should emergency exits be obstructed."),

    ("Inversion: Nowhere else", 4,
     "Nowhere else in the hemisphere ________ such ecological biodiversity.",
     ["will one encounter", "one will encounter", "encounters one", "one encounters"],
     "Fronted negative location adverb 'Nowhere else' triggers auxiliary inversion.",
     "Nowhere else can such ancient temperate rainforests be found."),

    ("Inverted Conditional: Had he but known", 5,
     "Had he ________ the perils that awaited him, he would never have entered the cavern.",
     ["but known", "even known", "yet known", "just knowing"],
     "'Had [subject] but known' is an archaic, literary inverted conditional meaning 'if only he had known'.",
     "Had we but realized the gravity of the situation, we would have sounded the alarm."),

    ("Subjunctive: Imperative that", 4,
     "It is imperative that the laboratory supervisor ________ all safety checklists before activation.",
     ["verify", "verifies", "verified", "must verify"],
     "Impersonal adjectives of urgency ('imperative that') govern the base subjunctive ('verify').",
     "It is imperative that every delegate register their credentials before voting."),

    ("Subjunctive: Crucial that", 4,
     "It is crucial that the ambassador ________ informed of all border developments immediately.",
     ["be", "is", "was", "would be"],
     "'It is crucial that' governs the base subjunctive 'be'.",
     "It is crucial that confidentiality be maintained throughout the negotiations."),

    ("Subjunctive: Stipulate that", 4,
     "The charter stipulates that every applicant ________ a certified police record.",
     ["submit", "submits", "submitted", "should submit to"],
     "Mandative verbs ('stipulate that') take the bare subjunctive.",
     "The treaty stipulates that borders remain open to humanitarian convoys."),

    ("Locative Inversion", 4,
     "Beyond the high stone perimeter ________ the sprawling vineyard estates of the baron.",
     ["lay", "did lie", "lying", "was laid"],
     "Locative prepositional phrase fronting triggers full inversion with intransitive verbs of position.",
     "At the end of the cobblestone alley stood a weathered seventeenth-century tavern."),

    ("Fronted Participle: Surrounded", 4,
     "________ by hostile critics, the novelist defended his controversial narrative choices with passion.",
     ["Surrounded", "Surrounding", "Having surrounded", "To be surrounded"],
     "Past participle phrase acting as a concessive/causal modifier to the subject.",
     "Protected by armed escorts, the foreign envoy reached the embassy safely."),

    ("Absolute Clause: Nominative", 5,
     "The summit ________ without an accord, both delegations prepared for trade tariffs.",
     ["having concluded", "has concluded", "concluded having", "having been conclude"],
     "Absolute nominative clause containing an independent participle construction.",
     "The tide having turned, the stranded fishermen were able to refloat their dory."),

    ("Cleft Sentence: It is precisely", 4,
     "It is precisely because of his stubborn integrity ________ voters respect him so profoundly.",
     ["that", "why", "which", "how"],
     "It-cleft focusing on a causal reason clause strictly takes 'that'.",
     "It is for this exact reason that safety inspections must never be rushed."),

    ("Pseudo-cleft: What remains", 4,
     "What ________ to be seen is whether the new coalition can maintain its parliamentary majority.",
     ["remains", "is remaining", "has remained", "to remain"],
     "Formulaic pseudo-cleft: 'What remains to be seen is...'.",
     "What remains to be determined is the exact cause of the structural failure."),

    ("Modal Deduction: Cannot fail to", 5,
     "Anyone visiting the ancient amphitheater ________ be overwhelmed by its majestic acoustics.",
     ["cannot fail to", "must fail to", "may not fail", "should fail to"],
     "'Cannot fail to' is an emphatic idiom expressing inevitable certainty or consequence.",
     "His extraordinary performance cannot fail to impress the judges."),

    ("Modal Deduction: Might well have", 4,
     "Without the thermal rescue blanket, the hypothermic climber ________ perished on the ledge.",
     ["might well have", "must well have", "could well", "would well"],
     "'Might well have + past participle' expresses high likelihood of an unfulfilled past outcome.",
     "She might well have won the tournament had she not sustained an ankle sprain."),

    ("Inversion: Not a single word", 4,
     "Not a single word ________ during the entire solemn ceremony.",
     ["did he utter", "he uttered", "uttered he", "he did utter"],
     "Fronted negative object/noun phrase triggers subject-auxiliary inversion.",
     "Not a single question did the journalists ask during the brief press conference."),

    ("Concessive Fronting: Try as he would", 5,
     "________ as he would, he could not undo the catastrophic damage caused by his betrayal.",
     ["Try", "Trying", "Tried", "To try"],
     "Bare infinitive + as + subject + modal verb creates an emphatic concessive clause.",
     "Strive as they might, the rescue team could not reach the stranded miners before nightfall."),

    ("Concessive Fronting: Strange though", 4,
     "Strange ________ it may seem, the desert blooms with thousands of wildflowers after flash floods.",
     ["though", "however", "although", "even"],
     "Adjective + though + subject + may/verb expresses concession.",
     "Unlikely though it sounds, the two former rivals became lifelong collaborators."),

    ("Correlative Comparative", 4,
     "The ________ the vintage port, the more nuanced its bouquet of dried figs and leather.",
     ["older", "more old", "elder", "oldest"],
     "Correlative comparative: 'The [comparative]..., the [comparative]...'.",
     "The more challenging the mountaineering route, the greater the climber's satisfaction upon summiting."),

    ("Subjunctive: Come what will", 4,
     "________ what will, we are determined to complete the cathedral restoration.",
     ["Come", "Comes", "Came", "May come"],
     "Formulaic subjunctive idiom expressing unconditional determination.",
     "Come what may, our team will deliver the software on the agreed deadline."),

    ("Inversion: Little did they suspect", 4,
     "Little ________ that the quiet librarian was actually an undercover intelligence operative.",
     ["did they suspect", "they suspected", "suspected they", "had they suspected"],
     "Fronted restrictive adverb 'Little' triggers auxiliary inversion.",
     "Little did we anticipate that the small startup would become a trillion-dollar enterprise."),

    ("Inversion: Scarcely had", 4,
     "Scarcely ________ the harbor when a sudden squall capsized two fishing trawlers.",
     ["had the fleet left", "the fleet had left", "left the fleet", "did the fleet leave"],
     "'Scarcely... when' mandates past perfect auxiliary inversion.",
     "Scarcely had the ink dried on the treaty when border skirmishes resumed.")
]

MORE_CONFUSABLES_ITEMS = [
    ("Elicit vs Illicit", 4,
     "The detective questioned the informant patiently in an attempt to ________ vital intelligence.",
     ["elicit", "illicit", "elicitation", "illicitly"],
     "'To elicit' means to draw out or evoke a reaction or fact. 'Illicit' means forbidden by law or rules.",
     "Her passionate lecture elicited enthusiastic applause from the graduate students."),

    ("Defective vs Deficient", 4,
     "The engineers discovered that the backup generator had a ________ cooling valve.",
     ["defective", "deficient", "defect", "deficiency"],
     "'Defective' means having a physical fault or flaw. 'Deficient' means not having enough of a necessary quality.",
     "The product recall was initiated because of a defective steering assembly."),

    ("Credible vs Credulous", 4,
     "Only a remarkably ________ investor would believe promises of guaranteed 50% weekly returns.",
     ["credulous", "credible", "creditably", "credulity"],
     "'Credulous' means having too great a readiness to believe things; gullible. 'Credible' means believable.",
     "Scammers prey upon credulous retirees with fictitious high-yield bond schemes."),

    ("Sensuous vs Sensual", 4,
     "The poet's verse was celebrated for its rich, ________ imagery depicting autumnal orchards.",
     ["sensuous", "sensual", "sensuality", "sensuously"],
     "'Sensuous' relates to aesthetic or poetic sensory appreciation. 'Sensual' relates to physical or sexual gratification.",
     "Keats is admired for the intense, sensuous texture of his odes."),

    ("Equable vs Equitable", 5,
     "The mediator proposed an ________ division of the contested marital assets.",
     ["equitable", "equable", "equitably", "equableness"],
     "'Equitable' means fair, just, and impartial. 'Equable' means calm, unvarying, or tranquil.",
     "The union negotiated an equitable distribution of overtime bonuses among all shifts."),

    ("Amoral vs Immoral", 4,
     "Algorithms themselves are ________ tools, but the ways humans deploy them have profound ethical weight.",
     ["amoral", "immoral", "amorality", "immorally"],
     "'Amoral' means lacking moral sensibility or outside the sphere of morality. 'Immoral' means morally wrong.",
     "Nature is inherently amoral, neither benevolent nor malicious towards mankind."),

    ("Discomfit vs Discomfort", 5,
     "The prosecutor's aggressive cross-examination did much to ________ the haughty witness.",
     ["discomfit", "discomfort", "discomfiture", "discomforted"],
     "'To discomfit' means to make someone feel confused, abashed, or embarrassed. 'Discomfort' is physical or mental unease.",
     "He was noticeably discomfited by questions concerning his foreign bank deposits."),

    ("Fulsome vs Copious", 5,
     "The author took ________ notes during her three months in the national archives.",
     ["copious", "fulsome", "copiously", "fulsomely"],
     "'Copious' means abundant in supply or quantity. 'Fulsome' means excessively complimentary or flattering.",
     "The botany student compiled copious field observations on alpine mosses."),

    ("Urbane vs Urban", 4,
     "The diplomat was known for his polished, ________ manners and sophisticated conversational style.",
     ["urbane", "urban", "urbanity", "urbanely"],
     "'Urbane' means suave, courteous, and refined in manner. 'Urban' relates to a city or town.",
     "Her urbane wit made her a sought-after dinner guest among ambassadors in Geneva."),

    ("Luxuriant vs Luxurious", 4,
     "The rainforest was blanketed in ________ vegetation that shielded the forest floor from the sun.",
     ["luxuriant", "luxurious", "luxuriance", "luxuriate"],
     "'Luxuriant' means rich and profuse in growth; lush. 'Luxurious' means characterized by opulence and comfort.",
     "The greenhouse was filled with luxuriant tropical ferns and rare orchids.")
]
